### ISSUE TITLE
Company mode problems

### ISSUE THREAD

**Issue by pragdave** [tonini/alchemist.el#105]
Trying to use company in iex on -V1.0. As I type, I see 

~~~
Error in process filter: Symbol's function definition is void: s-trim
~~~

If I hit tab to get a completion, I see

~~~
Company: Back end alchemist-company async timeout with args (candidates Enum.)
~~~

I'm sure this must me an issue with the way my emacs is set up, but I'm not sure where to start looking.

Cheers

Dave

**Comment by tonini** [comment]
Thanks for reporting this.

Do you running the currently master branch? (it's now 1.0.0)

Can I have a look at your Emacs config? maybe a gist from the `init.el` file?

**Comment by pragdave** [comment]
I just switched to master—same issue.

My emacs config is pretty large. Maybe to start with I can show you the high level stuff related to Elixir:

~~~
(setenv "PATH"
        (concat
         "/usr/local/bin:/Users/dave/Play/elixir/bin:"
         (getenv "PATH")))

(load-file "~/.emacs.d/custom/elixir.el")
(require 'elixir-mode)

(add-to-list 'load-path "~/.emacs.d/custom/alchemist.el/")
(require 'alchemist)

(add-hook 'elixir-mode-hook 'alchemist-mode)
(add-hook 'alchemist-iex-mode-hook '(lambda()
                                      (local-set-key (kbd "<tab>") 'company-complete)))

(setq company-idle-delay 0.1)
(setq company-tooltip-limit 10)
(setq company-minimum-prefix-length 2)
(setq company-tooltip-flip-when-above t)
~~~

**Comment by tonini** [comment]
@pragdave Ok I think I know what the issue was. I pushed the change to master, please pull and try again.

**Comment by pragdave** [comment]
You're a STAR! Works wonderfully.

Thanks

**Comment by tonini** [comment]
Great! :) Happy that it works now!

pragdave <notifications@github.com> schrieb am Di., 16. Juni 2015 11:47:
