### ISSUE TITLE
[] Balancing breaks when contents in regex contain a #

### ISSUE THREAD

**Issue by redvers** [tonini/alchemist.el#108]
Minimal case:

defmodule Demo do
  def function do
    Regex.match?(~r/[#]/, "hello")
  end
end

Thanks,

Red

**Comment by tonini** [comment]
Hi @redvers 

This isn't a Alchemist issue.

Alchemist brings the Elixir tooling into Emacs, so its a minor mode for Emacs.
For indentation and syntax highlighting is the Elixir-Mode where you can find here https://github.com/elixir-lang/emacs-elixir

Could you please open up an issue about that case on the Elixir-Mode repository?

That would be great!

Thanks

**Comment by redvers** [comment]
Moved - thanks.
