### ISSUE TITLE
Cant get alchemist mode to work

### ISSUE THREAD

**Issue by larryweya** [tonini/alchemist.el#109]
I'm new to both Elixir and Alchemy. I installed Emacs for OSX, added the elpa repo by adding this to my ~/.emacs.d/init.el

```el
(when (>= emacs-major-version 24)
  (require 'package)
  (add-to-list
   'package-archives
   '("melpa" . "http://melpa.org/packages/")
   t)
  (package-initialize))
```

I then installed company followed by alchemist (and got some warnings about the company backend).

```
In alchemist-company:
alchemist-company.el:60:23:Warning: misplaced interactive spec: `(interactive
    (company-begin-backend (quote alchemist-company)))'
alchemist-company.el:60:23:Warning: value returned from (string= mode-name
    "Alchemist-IEx") is unused
alchemist-company.el:74:31:Warning: assignment to free variable
    `alchemist-server-company-callback'

In end of data:
alchemist-company.el:84:1:Warning: the following functions are not known to be defined:
    alchemist-help--execute-without-complete,
    alchemist-goto--open-definition, case, init, prefix,
    alchemist-help--exp-at-point, doc-buffer, location, candidates,
    alchemist-server-complete-candidates, annotation

Compiling file /Users/larry/.emacs.d/elpa/alchemist-20150616.2147/alchemist-compile.el at Thu Jun 18 00:24:53 2015

In end of data:
alchemist-compile.el:74:1:Warning: the following functions are not known to be defined:
    alchemist-buffer-run, alchemist-utils--build-runner-cmdlist

Compiling file /Users/larry/.emacs.d/elpa/alchemist-20150616.2147/alchemist-complete.el at Thu Jun 18 00:24:53 2015

In end of data:
alchemist-complete.el:114:1:Warning: the function
    `alchemist-utils--count-char-in-str' is not known to be defined.

Compiling file /Users/larry/.emacs.d/elpa/alchemist-20150616.2147/alchemist-eval.el at Thu Jun 18 00:24:54 2015

In alchemist-eval-print-buffer:
alchemist-eval.el:141:43:Warning: `end-of-buffer' is for interactive use only;
    use `(goto-char (point-max))' instead.

In end of data:
alchemist-eval.el:186:1:Warning: the following functions are not known to be defined:
    alchemist-project-p, alchemist-project--establish-root-directory,
    alchemist-eval--build-code-evaluation-command,
    alchemist-utils--remove-newline-at-end,
    alchemist-eval--build-code-evaluation-as-quoted-command,
    alchemist-server-eval, alchemist-server-eval-and-insert,
    alchemist-server-eval-quote,
    alchemist-server-eval-quote-and-insert

Compiling file /Users/larry/.emacs.d/elpa/alchemist-20150616.2147/alchemist-execute.el at Thu Jun 18 00:24:54 2015

In end of data:
alchemist-execute.el:74:1:Warning: the following functions are not known to be defined:
    alchemist-buffer-run, alchemist-utils--build-runner-cmdlist

Compiling file /Users/larry/.emacs.d/elpa/alchemist-20150616.2147/alchemist-goto.el at Thu Jun 18 00:24:55 2015

In alchemist-goto--string-at-point-p:
alchemist-goto.el:149:29:Warning: `end-of-buffer' is for interactive use only;
    use `(goto-char (point-max))' instead.
alchemist-goto.el:154:29:Warning: `end-of-buffer' is for interactive use only;
    use `(goto-char (point-max))' instead.

In alchemist-goto--open-file:
alchemist-goto.el:288:6:Warning: `beginning-of-buffer' is for interactive use
    only; use `(goto-char (point-min))' instead.

In end of data:
alchemist-goto.el:345:1:Warning: the function `alchemist-server-goto' is not
    known to be defined.
```

I have an existing project created using mix new. I've tried to load the mix.es file as well as modules in my lib dir but I always have to manually enable alchemist-mode. I don't get any syntax highlighting or auto-complete. What am I doing wrong?

**Comment by tonini** [comment]
Hi @larryweya 

It's seems you have kind of an Emacs/Elixir/Alchemist setup issue.

Let's fix that :+1: 

1. Could you please create a https://gist.github.com/ file of you complete emacs config.
2. Which Emacs did you install, I'm wondering because if you have a latest one you don't even have to check in the config about 24 > version to be sure package.el is available. (means less logic in the config :+1: )

I can help you to create a raw basic emacs `init.el` with a elixir/alchemist/company setup, but I need the informations mentioned above. 

Thanks

**Comment by larryweya** [comment]
@tonini Thanks for getting back to me so fast.

Here is the gist https://gist.github.com/larryweya/60af57fbbdca44ffc46a

I downloaded emacs from http://emacsformacosx.com/ and the version from M-x emacs-version is 24.5.1

My elixir is version 1.0.3 though I wouldnt think this would cause the issue.

**Comment by tonini** [comment]
@larryweya 

Thanks for sending the informations.

Ok, here you have an updated `init.el` 

If is not working at the first place, its because you havent installed the company, alchemist or elixir-mode package. So you need to call  the `package-list-packages` function to get a fresh pull from the package repositories (MELPA and MELPA-STABLE) and after that you can `package-install` and install the packages.

config: https://gist.github.com/tonini/acc154a1d8d182a487bd

**Comment by larryweya** [comment]
@tonini this works, it now enables alchemist mode when I load a file within the project. I had to remove and re-install all the packages since autocomplete still wasnt working (`Company back-end 'alchemist-company' could not be initialized:
Symbol's function definition is void: init`). I used company mode from the stable channel this time.

Thanks for your help and for the tool.

**Comment by tonini** [comment]
Great! You're welcome. :+1:
