### ISSUE TITLE
Company mode doesn't work with alchemist

### ISSUE THREAD

**Issue by Magellanea** [tonini/alchemist.el#117]
I've tried to install the two packages ```elixir-mode``` and ```alchemist``` both from Melpa and manually, however I'm unable to make autocomplete work with company mode as expected.
Whenever I try to make it autocomplete I get the following lines
<code>
Company: An error occurred in auto-begin

Buffer test.exs has no process
</code>

**Comment by tonini** [comment]
hi @Magellanea 

This issue is already know. Please update to at least Emacs version 24.4 to fix the subprocess issue.

Please report if it works for you then.

**Comment by Magellanea** [comment]
@tonini Done and working perfectly :+1: 

Is there's a place to report this as a faq or was there a place I missed from the first place.

**Comment by tonini** [comment]
@Magellanea glade it works for you now! :+1: 

The problem occurred the first time last week and I forgot to mention the dependency on the [README](https://github.com/tonini/alchemist.el#requirements).

Apart from that, you should find all informations on the [README](https://github.com/tonini/alchemist.el)

Cheers
