### ISSUE TITLE
Server crash when Emacs run from a desktop (not terminal)

### ISSUE THREAD

**Issue by wrachwal** [tonini/alchemist.el#123]
When I start Emacs from a desktop (Alt+F2 in ubuntu), the alchemist-server crashes on any attempts of its first use (e.g. M-. has no effect on resolvable symbols), and in *alchemist-server* buffers I see the following trace record:

> {"init terminating in do_boot",{{badmatch,{error,{elixir,{bad_return,{{elixir,start,[normal,[]]},{'EXIT', {{badmatch,{error,enotsup}},[{elixir,start,2,[{file,"src/elixir.erl"},{line,34}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}]}}}}}}},[{elixir,start_cli,0,[{file,"src/elixir.erl"},{line,56}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
>
> Crash dump is being written to: erl_crash.dump...done
> init terminating in do_boot ()
> 
> Process /root-dir-of-mix-project/ exited abnormally with code 1

Alchemist has no problems with Emacs started from a terminal (both GUI and textual (-nw)).

I use Elixir built from master branch
* master 09930b5 Set proxy options for the correct URI scheme

and Emacs built from sources (stable, 24.5.1).

**Comment by tonini** [comment]
Hi @wrachwal 

Maybe this has something to do with https://github.com/elixir-lang/elixir/issues/3228

Could you please have a look and check this?

Thanks

**Comment by wrachwal** [comment]
Yes, the stacktrace is identical. Below what I got when running `M-x alchemist-iex-run` (note Erlang is R18.0):

```
Warning: could not run smart terminal, falling back to dumb one
Eshell V7.0  (abort with ^G)

=INFO REPORT==== 1-Jul-2015::21:54:59 ===
    application: elixir
    exited: {bad_return,
                {{elixir,start,[normal,[]]},
                 {'EXIT',
                     {{badmatch,{error,enotsup}},
                      [{elixir,start,2,[{file,"src/elixir.erl"},{line,34}]},
                       {application_master,start_it_old,4,
                           [{file,"application_master.erl"},{line,273}]}]}}}}
    type: temporary

=INFO REPORT==== 1-Jul-2015::21:54:59 ===
    application: syntax_tools
    exited: stopped
    type: temporary

=INFO REPORT==== 1-Jul-2015::21:54:59 ===
    application: compiler
    exited: stopped
    type: temporary

=INFO REPORT==== 1-Jul-2015::21:54:59 ===
    application: crypto
    exited: stopped
    type: temporary

=ERROR REPORT==== 1-Jul-2015::21:54:59 ===
Error in process <0.26.0> with exit value:
{{badmatch,
     {error,
         {elixir,
             {bad_return,
                 {{elixir,start,[normal,[]]},
                  {'EXIT',
                      {{badmatch,{error,enotsup}},
                       [{elixir,start,2,[{file,"src/elixir.erl"},{line,34}]},
                        {application_master,start_it_old,4,
                            [{file,"application_master.erl"},
                             {line,273}]}]}}}}}}},
 [{'Elixir.IEx',start_iex,0,[{file,"lib/iex.ex"},{line,469}]},
  {'Elixir.IEx','-start/2-fun-0-',2,[{file,"lib/iex.ex"},{line,455}]}]}
```

**Comment by tonini** [comment]
Hm, maybe there is a path problem.

For example, `alchemist-iex-run` just runs `iex` through `comint`. 

So could you please test the start of `iex` for example inside `ansi-term` or `shell`?

The thing is, if you run alchemist in the terminal, it works. If you run it in emacs GUI it won't. So I would say there is a problem with the call of `elixir` command (alchemist server starts with the `elixir` command) and I guess the `elixir` command is wrong in the PATH environment variable.

Could you try to test that a bit?

**Comment by wrachwal** [comment]
No, it's rather not a path problem (note elixir/iex in the stacktrace).

It's not that in GUI it doesn't work; it does but only when GUI Emacs is launched from a terminal (`emacs &`), so the problem has something to do with initialization of the terminal functionality by Emacs process when Emacs program is started from a desktop (via `Alt+F2` shortcut in Ubuntu).

So, only with Emacs started from a desktop I have problems.
Inside it, I did another check, as you advised, from `ansi-term` and `shell` and you know what?... `iex` started without problems...

Well, later today (it's time to start _the day job_ now, fortunately with Elixir ;)) I will put some debug stuff in Elixir code around the place where it croaks, and we'll see what happens...

**Comment by wrachwal** [comment]
Hi @tonini 

You were right! I had quite old (about which I've quite forgotten) elixir in the path, and Emacs started from a terminal used basically a version built from the _master_ branch. Sorry!

**Comment by tonini** [comment]
Hi @wrachwal 

Thats great, I'm glad that it worked out in the end :+1: 

Cheers
