### ISSUE TITLE
Company didn't work in elixir file

### ISSUE THREAD

**Issue by Cifer-Y** [tonini/alchemist.el#134]
In my init.el
```
(require 'company)
(require 'elixir-mode)
(require 'alchemist)
(require 'elixir-mode)
(require 'ruby-end)
(add-to-list 'elixir-mode-hook
             (defun auto-activate-ruby-end-mode-for-elixir-mode ()
               (set (make-variable-buffer-local 'ruby-end-expand-keywords-before-re)
                    "\\(?:^\\|\\s-+\\)\\(?:do\\)")
               (set (make-variable-buffer-local 'ruby-end-check-statement-modifiers) nil)
               (ruby-end-mode +1)))

(add-hook 'after-init-hook 'global-company-mode)
(add-hook 'elixir-mode-hook 'alchemist-mode)
```

It can work well in other file, such as:
![cifer init el emacs today at 00 20](https://cloud.githubusercontent.com/assets/4470516/8634458/e27c71cc-282b-11e5-8332-5cbf11b9ecaf.png)

But in elixir file, no matter if the file is in a mix project , just perform like below:
![123](https://cloud.githubusercontent.com/assets/4470516/8634464/1a04a8c6-282c-11e5-8ccc-b11117e188d5.png)

Just nothing happened... no error, no warning, no  completion

**Comment by tonini** [comment]
Hi, 

Im currently in the mountains with just mobile internet :-)

But I try my best to help.

First, you don't need to use a hook to initialr alchemist at all. Just the following will work sane:

```el
(require 'elixir-mode)
(require 'alchemist-mode)
```

Othereise you call `alchemist-mode` twice anf it disable it again.

I hope that helps

Cheers from the top of Switzerland.

**Comment by Cifer-Y** [comment]
Still not work, I’ll try another solution, and wish you have a nice day :-)

—

**Comment by tonini** [comment]
Hey

Ok that sounds the the Alchemist-Server doesnt run at all. Please check the
function `list-procesess` after you open an Elixir file and chech if there
is running a Server for the current mix project or an independent server.
When not, then the problem is on another placd than the init setup.

Check the Emacs version, it needs at least 24.4
Check that the correct installed elixir will run inside Emacs, check the
environment variables.


Cifer-Y <notifications@github.com> schrieb am So., 12. Juli 2015 07:36:

**Comment by Cifer-Y** [comment]
Yes, you are right, when I run `list-processess`, there is no process at all.
And my emacs version is correct, it is 24.5.
But I don't know how to "Check that the correct installed elixir will run inside Emacs, check the
environment variables",  will you do me a favor?

**Comment by tonini** [comment]
Check in `which elixir` i the terminal and then run `shell-command` with
the same `which` command to see what emacs runs for elixir, is it the same
as in the terminal? Then check the `alchemist-server-command` variable and
run the output in the terminal and you see if the server start or what
error you get.

Cifer-Y <notifications@github.com> schrieb am So., 12. Juli 2015 08:27:

**Comment by Cifer-Y** [comment]
I run `which elixir` in my terminal I can get ‘/usr/local/bin/elixir’, but in emacs, the result is ‘elixir not found’.And I’m sorry I don’t know how to check the `alchemist-server-command` variable.


—

**Comment by tonini** [comment]
Ah ok we got the problem, are you using osx?

Cifer-Y <notifications@github.com> schrieb am So., 12. Juli 2015 08:50:

**Comment by Cifer-Y** [comment]
Yes，I’m using OSX 10.11


—

**Comment by tonini** [comment]
Please check https://github.com/purcell/exec-path-from-shell :)

Cifer-Y <notifications@github.com> schrieb am So., 12. Juli 2015 08:56:

**Comment by Cifer-Y** [comment]
Okay, wait for my good news :P

—

**Comment by Cifer-Y** [comment]
Thank you for you patience, it seems a tiny question, just a path problem. Thank you for your patience again.

**Comment by tonini** [comment]
Great, Im glad it works now. Have fun :-)

Cifer-Y <notifications@github.com> schrieb am So., 12. Juli 2015 09:46:

**Comment by Cifer-Y** [comment]
Excuse me, I have a little question.


`(setq alchemist-goto-elixir-source-dir "/path/to/elixir/source/“)`
How can I find the elixir source dir ?



—

**Comment by whatyouhide** [comment]
Hey @Cifer-Y, maybe this issue isn't the best place to ask questions unrelated with it. You're welcome to open another issue, but for questions you're more than welcome on IRC (#elixir-lang and #emacs-elixir) or in the #emacs Slack channel (https://elixir-slackin.herokuapp.com). Thanks :)

**Comment by tonini** [comment]
If you're using homebrew the source is automaticly deleted after installing
elixir and erlang, so you need to download thr source to a separate place
on your system and add the path to the variable. In linux for example I
dont need to do this becausd I compile elixir and erlang by hand.

Andrea Leopardi <notifications@github.com> schrieb am So., 12. Juli 2015
14:52:

**Comment by Cifer-Y** [comment]
Okay，I got it, thank you very much for your advice

On Sun, Jul 12, 2015 at 20:52 Andrea Leopardi <notifications@github.com>
wrote:

> Hey @Cifer-Y <https://github.com/Cifer-Y>, maybe this issue isn't the
> best place to ask questions unrelated with it. You're welcome to open
> another issue, but for questions you're more than welcome on IRC
> (#elixir-lang and #emacs-elixir) or in the #emacs Slack channel (
> https://elixir-slackin.herokuapp.com). Thanks :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tonini/alchemist.el/issues/134#issuecomment-120718877>
> .
>
-- 
Cifer
