### ISSUE TITLE
Failure to initialize company-backend

### ISSUE THREAD

**Issue by hectoregm** [tonini/alchemist.el#142]
When I try to start the company backend

Company back-end 'alchemist-company' could not be initialized:
Wrong type argument: stringp, (:eval (propertize "Elixir" (quote face) alchemist-test--mode-name-face))

Stacktrace

```lisp
Debugger entered--Lisp error: (wrong-type-argument stringp (:eval (propertize "Elixir" (quote face) alchemist-test--mode-name-face)))
  alchemist-company(prefix)
  #[0 "\n\203	\nC\202\n\211\205\233\211@\3009\204\306!\203<9\2036\307N\310=\2046\307N?\205@\311!\205@\312!\202@\313\312\"\240\210\300\242\203\224\314\300\242!\203\216\315\300\242!\211\301\316\f!\240\210\301\242:\204w
\203i\317\320!\210\301\242\310=\203\216\321\322!\210\202\216
\203\300\242\323\301\242!\210\324\325\326 \"\210\327\330!\210\331\332\301\242\"\210A\266\202\202\n\207" [(nil) (nil) company-backend company-backends company-prefix company--manual-action functionp company-init t company-init-backend prefix company--multi-backend-adapter company--good-prefix-p company--prefix-str company-calculate-candidates message "No completion found" company-cancel unique company-update-candidates run-hook-with-args company-completion-started-hook company-explicit-action-p company-call-frontends show throw --cl-block-nil-- company--manual-prefix] 6 "\n\n(fn)"]()
  funcall(#[0 "\n\203	\nC\202\n\211\205\233\211@\3009\204\306!\203<9\2036\307N\310=\2046\307N?\205@\311!\205@\312!\202@\313\312\"\240\210\300\242\203\224\314\300\242!\203\216\315\300\242!\211\301\316\f!\240\210\301\242:\204w
\203i\317\320!\210\301\242\310=\203\216\321\322!\210\202\216
\203\300\242\323\301\242!\210\324\325\326 \"\210\327\330!\210\331\332\301\242\"\210A\266\202\202\n\207" [(nil) (nil) company-backend company-backends company-prefix company--manual-action functionp company-init t company-init-backend prefix company--multi-backend-adapter company--good-prefix-p company--prefix-str company-calculate-candidates message "No completion found" company-cancel unique company-update-candidates run-hook-with-args company-completion-started-hook company-explicit-action-p company-call-frontends show throw --cl-block-nil-- company--manual-prefix] 6 "\n\n(fn)"])
  company--begin-new()
  company--perform()
  #[0 "\301 \210\207" [company-candidates company--perform] 1 "\n\n(fn)"]()
  funcall(#[0 "\301 \210\207" [company-candidates company--perform] 1 "\n\n(fn)"])
  company-auto-begin()
  company-idle-begin(#<buffer *scratch*> #<window 3 on *scratch*> 11 5)
  apply(company-idle-begin (#<buffer *scratch*> #<window 3 on *scratch*> 11 5))
  byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 21933 34552 523629 nil company-idle-begin (#<buffer *scratch*> #<window 3 on *scratch*> 11 5) nil 0])
```

**Comment by hectoregm** [comment]
Fixed when I installed elixir-mode, maybe add it to the installation notes ?

**Comment by tonini** [comment]
hi @hectoregm 

You never have to `(require 'alchemist-company)` by hand. Like you see it in the [Installation](https://github.com/tonini/alchemist.el#installation) section, just `(require 'alchemist)` and everything will be loaded. You can't just require different parts of the codebase of Alchemist.

About the `elixir-mode` installation, `elixir-mode` is the Elixir language major mode for Emacs and you will need it if you start working with Elixir and Emacs. Alchemist is a minor mode with brings the Elixir Tooling into Emacs. 

Alchemist will just be initialized through the load of Elixir files via `elixir-mode`. And until now it was no need to mentation the installation about `elixir-mode` on the Alchemist `README` because, without `elixir-mode` you won't programming Elixir on Emacs at all.

Could you show me how you tried to initialize Alchemist at the beginning?

**Comment by hectoregm** [comment]
Well I didn't do it by hand but when loading the alchemist mode with M-x alchemist-mode given i didn't have elixir-mode at first. I think a minor note about needing elixir-mode will be of help because at least for me I thought that getting alchemist-mdoe through MELPA was going to bring along elixir-mode.

**Comment by tonini** [comment]
Please give it another try, I added `elixir-mode` as Package-Dependency. Now you just need to `(require 'alchemist)` and don't have to know anything about `elixir-mode`.

**Comment by tonini** [comment]
I will close this issue because now `Alchemist` depends on `elixir-mode` inside the `Package-Dependencies` and that get handled by `package.el` by itself. 

So if you install just `Alchemist`, `elixir-mode` will get installed too if not already available.

Thanks for the report.
