### ISSUE TITLE
Clarification in readme

### ISSUE THREAD

**Issue by diogovk** [tonini/alchemist.el#145]
As a new user to emacs, I was confused by why wansn't alchemist working in my setup.
I installed it using package-install, but after restarting emacs alchemist commands were not being recognized.
Turns out you have to `(require 'alchemist)`, which is an instruction which is in the topic "Manual installation".
I'm pretty sure that step is necessary for automatic installation as well.

Or am I mistaken?

**Comment by tonini** [comment]
Hi @diogovk 

If you installed `Alchemist` with `package-install` it will be loaded at Emacs startup. That's how `package.el` works by default. But if you have the variable `package-enable-at-startup` set to `nil` that won't happen and you need to `(require 'alchemist)` manual by hand.

Did you try to call `Alchemist` functions inside an Elixir file? `Alchemist` mode will just be enabled inside Elixir files, maybe that could be the issue?

**Comment by diogovk** [comment]
That's weird I've just commented and it stopped working again. (`C-c a is undefined` while editing .exs file).
I checked with C-h v and it tells me that "Its value is t" for package-enable-at-startup.

This is my .emacsrc:

```
; Use the package manager
(require 'package)

; Sets package management sources
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)

; Initialize the package manager
(package-initialize)

(require 'undo-tree)

(add-to-list 'load-path "~/.emacs.d/evil")
(require 'evil)
(evil-mode 1)

; (require 'alchemist)
```
I think I know what happened. I didn't install using `package-install` but `package-list-packages`.
I think installing this way requires that I enable manually.
