### ISSUE TITLE
alchemist-20150820.941.tar: Not found

### ISSUE THREAD

**Issue by rizafahmi** [tonini/alchemist.el#159]
Trying to install throug package-install, but got an error: `http://melpa.org/packages/alchemist-20150820.941.tar: Not found `

**Comment by tonini** [comment]
Hi,

It looks like you have an old package cache. Please call `package-list-packages` which fetches the last builds and you should get `MELPA Alchemist 20150824.223`.

**Comment by zhongwencool** [comment]
@tonini  it worked!!!

**Comment by tonini** [comment]
great! :+1: 

I close this issue now.

**Comment by rizafahmi** [comment]
Yes, it works!
