### ISSUE TITLE
alchemist-iex-send-region raises syntax error when region spans multiple lines

### ISSUE THREAD

**Issue by manukall** [tonini/alchemist.el#160]
example:
when i select the following and sent that to iex
```
sum = 1 + 1
IO.puts sum
```
the result is
```
** (SyntaxError) iex:1: syntax error before: IO
```

**Comment by tonini** [comment]
Thanks for the report. :+1:

**Comment by gleb** [comment]
That's because my-alchemist-iex--send-command strips newlines from input breaking syntax in cases like these:

```elisp
(defun alchemist-iex--send-command (proc str)
  (let ((str-no-newline (concat (alchemist-iex--remove-newlines str) "\n"))
     .....
      (comint-send-string proc str-no-newline))))
```

Which appears to be a workaround for comint+IEx not being able to handle multi-line input.   See #56 
#56 would need to resolved before this workaround is removed.

**Comment by tonini** [comment]
@manukall is fixed on master

**Comment by manukall** [comment]
@tonini thanks :+1:
