### ISSUE TITLE
Alchemist 20150826.817 + Elixir 1.1.0-dev: SyntaxError in alchemist-server

### ISSUE THREAD

**Issue by henrythebuilder** [tonini/alchemist.el#161]
Hi,
Using Alchemist 20150826.817 (with Elixir 1.1.0-dev), when starting *alchemist-mode*, *alchemist-server* buffer report a syntax error:

```
** (SyntaxError) .../.emacs.d/elpa/alchemist-20150826.817/alchemist-server/lib/source.exs:16: unexpected comma. Parentheses are required to solve ambiguity in nested calls.

This error happens when you have nested function calls without parentheses. For example:

    one a, two b, c, d

In the example above, we don't know if the parameters "c" and "d" apply to the function "one" or "two". You can solve this by explicitly adding parentheses:

    one a, two(b, c, d)

Elixir cannot compile otherwise. Syntax error before: ','
    (elixir) lib/code.ex:363: Code.require_file/2
    .../.emacs.d/elpa/alchemist-20150826.817/alchemist-server/lib/server.exs:3: (file)
    (elixir) lib/code.ex:363: Code.require_file/2
```
Following the message I try to change the line 16 in *source.exs* from
 ```module = Enum.filter(imports, &Informant.has_function? &1, function)```
to
``` module = Enum.filter(imports, &Informant.has_function?(&1, function))```

and it seem to work.
Is it a reasonable change ?
Thanks in advance
Enrico

**Comment by tonini** [comment]
Hi @henrythebuilder 

Thanks a lot for finding this issue.

I updated the `server.exs` with your solution. -> https://github.com/tonini/alchemist.el/commit/61f9b196c945b8eba013fd2c3469ef1913c67de4

You need to wait until http://melpa.org/ built the actual master as a package until you can `package-install` the fixed version.

Or you just clone the Alchemist repository and add it to the emacs load path if you can't wait until then :)

Thanks you! :yellow_heart: :green_heart: :blue_heart:

**Comment by henrythebuilder** [comment]
Thanks for update,
I just updated to Alchemist 20150827.503 with no problem :thumbsup:

**Comment by tonini** [comment]
Great! Thanks a lot for the report :-) :heart:
