### ISSUE TITLE
"No test file found; create new one?" in Phoenix project.

### ISSUE THREAD

**Issue by hunterboerner** [tonini/alchemist.el#163]
In Phoenix projects, the code is stored under the `web` directory. Even if I have a test file for a controller, typing `C-c a p o` will ask me if I want to create a new test file. If I say yes, it creates the file in the same directory that the controller file is in. Is this due to Phoenix code going in `web`?

**Comment by tonini** [comment]
Hi,

Yes we're aware of this problem. Currently we have no `Phoenix` support in case of the `web` directory but I'm working on the `alchemist-project` refining which should also bring support for `Phoenix` directory structure.

Thanks

**Comment by tonini** [comment]
@hunterboerner The `alchemist-phoenix-mode` is now implemented on master (https://github.com/tonini/alchemist.el/pull/175) and handles this cases.

Thanks for the report

**Comment by hunterboerner** [comment]
Thank you!
