### ISSUE TITLE
Symbol's function definition is void: alchemist-compile*

### ISSUE THREAD

**Issue by Jansemon** [tonini/alchemist.el#166]
I installed all necessary packages and everything seems to work - e.g. auto completion, iex, switching between source and test source... although I need to enable company-mode manually, even when alchemist is loaded.

But the alchemist-compile functions all raise above mentioned error. I tried the packages from MELPA and MELPA STABLE, but to no avail.

I'm using emacs 24.5.1 and elixir 1.0.5. 

My ~/.emacs file:

    (custom-set-variables <omitted>)
    (custom-set-faces <omitted>)

    (require 'package)
    (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
    (add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/"))

    (package-initialize)

    (require 'elixir-mode)
    (require 'alchemist)

The following packages are installed:

    alchemist          1.5.0        
    async              1.4          
    company            0.8.12       
    dash               2.11.0       
    elixir-mode        20150914.1212
    epl                20150517.433 
    evil               1.2.4        
    flx                0.5          
    goto-chg           20131228.659 
    pkg-info           0.6          
    undo-tree          20140509.522 

I'm sorry if this is just a stupid on my part, but any help would be appreciated.

Thanks in advance and best regards...

**Comment by gausby** [comment]
Hi. I think that this issue was solved yesterday, but it might not be on melpa stable yet:

https://github.com/tonini/alchemist.el/commit/2ec05caa8d0e3b8e886c4dc5daf23b3ed3303b9b

**Comment by Jansemon** [comment]
Hm... ok, I will try again with the one from MELPA, since I think I tried the non-stable version sometimes yesterday....

**Comment by gausby** [comment]
:)

I don't know if it will solve the problem, but you could try patching it temporary by executing:
```elisp
(require 'alchemist-compile)
```
After you have required alchemist.

**Comment by Jansemon** [comment]
ok, thanks a lot... the non-stable seems to have fixed it and your solution helps as well. :)

**Comment by tonini** [comment]
Hey @Jansemon 

As @gausby already mentioned, the fix was merged yesterday but just on master and MELPA. So I didn't release a patch version so far, sorry for that. :)

Thanks for your appreciation.
