### ISSUE TITLE
void-variable alchemist-project-compile-when-needed

### ISSUE THREAD

**Issue by andreas-roehler** [tonini/alchemist.el#168]
Accessing the menu results in:

Debugger entered--Lisp error: (void-variable alchemist-project-compile-when-needed)

;;;;;;

at

commit e51a2670d8c5b7f46b10d9b333f1263df630bc92
Author: Samuel Tonini <tonini.samuel@gmail.com>
Date:   Sat Sep 19 19:26:32 2015 +0200

    Increase readability with assignment in param area

**Comment by tonini** [comment]
Hi @andreas-roehler 

Thanks for the report! It's fixed on master now. https://github.com/tonini/alchemist.el/commit/3f1bf0d24f3a8c3a08ce9713c970d0b118d71482

:+1: 

Cheers
