### ISSUE TITLE
Change keymap bindings

### ISSUE THREAD

**Issue by tonini** [tonini/alchemist.el#17]
After using the bindings I realized that they're too long, we should think about it how we could trim them down a bit.

/cc @pragdave

**Comment by nixusr** [comment]
:+1:

**Comment by rranelli** [comment]
:+1: just please.

I've rebound (is that even a word ?) the whole thing myself

**Comment by tonini** [comment]
@rranelli do you have any recommendations? :)

**Comment by rranelli** [comment]
I've been using <kbd>C-c ,</kbd> myself, mostly because <kbd>c</kbd> and <kbd>,</kbd> are in opposite sides of the keyboard (for the folks with qwerty at least.)

I don't see much need to change the default prefix as long as the user is able to change it (and yes, my PR is still pending xD)

**Comment by rranelli** [comment]
See #77
