### ISSUE TITLE
Lack of autocompletion and parenthesis completion in REPL

### ISSUE THREAD

**Issue by Immortalin** [tonini/alchemist.el#171]
Can autocompletion and parenthesis completion be added for the REPL?

**Comment by tonini** [comment]
Hi @Immortalin 

What do you mean with lack of autocompletion in `REPL`? Do you mean inside an `alchemist-iex-run` created buffer? The completion is activated by default for this kind of buffer with alchemist, if not there might be an issue within your emacs config. Could you post a gists with your Emacs/Elixir config?

Parenthesis completion is a Emacs related thing, you might want to use something like [Smartparens](https://github.com/Fuco1/smartparens)

Cheers

**Comment by Immortalin** [comment]
I am using the elixir configuration layer from spacemacs

**Comment by Immortalin** [comment]
zohaib.me/spacemacs-and-alchemist-to-make-elixir-of-immortality/

**Comment by tonini** [comment]
@Immortalin as I can see in the article it's enables the `company-mode` just inside the `alchemist-mode` maybe make it global or ask in the emacs slackIO channel, there are many spacemacs users around.

**Comment by Immortalin** [comment]
Thanks for your help!

**Comment by zabirauf** [comment]
@Immortalin to enable company-mode globaly replace `(add-hook 'alchemist-mode-hook 'company-mode)` with `(global-company-mode)` and then reload the config `SPC f e R` and you should now have elixir auto completion in IEx buffer as well.

**Comment by Immortalin** [comment]
@zabirauf thanks!
