### ISSUE TITLE
Lookup does not work if alias is used

### ISSUE THREAD

**Issue by rogergl** [tonini/alchemist.el#172]
I could jump  to registration_changeset (M-.) if no alias is used ( MyProject.User.registration_changeset) but not to  User.registration_changeset
if I used "alias MyProject.User".

**Comment by tonini** [comment]
@rogergl I need to see the code for this to get idea what the issue could be.

Could you push the source to Github so I could have a look?

Thanks for reporting! :+1:

**Comment by rogergl** [comment]
Just trying to come up with a test case but I can no longer reproduce this problem.

**Comment by rogergl** [comment]
My assumption about the alias was wrong. Given the following source, looking up User.changeset works, looking up Rumble.Auth.login doesn't.
```
defmodule Rumble.UserController do
  require Logger

  alias Rumble.User

  use Rumble.Web, :controller

  plug :authenticate when action in [:index, :show]

  def index(conn, _params) do
    users = Repo.all(Rumble.User)
    render conn, "index.html", users: users
  end

  def show(conn, %{"id" => id}) do
    user = Repo.get(Rumble.User, id)
    render conn, "show.html", user: user
  end

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"user" => user_params}) do

    changeset = User.registration_changeset(%User{}, user_params)

    case Repo.insert(changeset) do

      {:ok, user} ->
        conn
        |> Rumble.Auth.login(user)
        |> put_flash(:info, "#{user.name} created|||!")
        |> redirect(to: user_path(conn, :index))

      {:error, changeset} ->
        render conn, "new.html", changeset: changeset

    end

  end

  defp authenticate(conn, _opts) do

    if conn.assigns.current_user do
      conn
    else
      conn
      |> put_flash(:error, "You must be logged in to access that page")
      |> redirect(to: page_path(conn, :index))
      |> halt()
    end

  end

end
```

**Comment by tonini** [comment]
To search for the issue here I really need the codebase, without there is no way to locate the issue. Could you push the source on Github?

Btw, you need to be sure that the codebase is compiled, without the proper `BEAM` files `Alchemist` can't find the source of the expression you try to jump to (`Rumble.Auth.login`). So be sure you compiled your `Mix` project.

And as I already mentioned, if it still not working I need the codebase to search for the place where the issue happens.

Thanks for the report :+1:

**Comment by rogergl** [comment]
Thanks for the help. I run sex -S mix to create the beam files and now M-. works.

**Comment by tonini** [comment]
@rogergl Great to hear that it works in the end. :+1:
