### ISSUE TITLE
Run latest cached test run

### ISSUE THREAD

**Issue by tonini** [tonini/alchemist.el#183]
**From irc**

> @gausby: being able to run a single unit test is neat and all, but it would be nice if I could "pin" a specific test, so I could call that one test from within the implementation code
@gausby: I think: standing in the test code, go to the test case; execute command that will pin the test at point; go to implementation file, run pinned-test-command; it will execute the pinned test only.

I like the idea and I know from my workflow that these is a nice behaviour. I wrote a package to handle these kind of case independent from the language. https://github.com/tonini/tester.el It's still kind of beta but it works very well.

Currently we have the function `alchemist-mix-rerun-last-test` to rerun the latest cached test run. But you have to call that function specifically though. What we could to is add the behaviour that it rather will call `alchemist-mix-rerun-last-test` by default if we're not in an Elixir test file at all. So if you run a test and switch to the file under test and just call the test again, it would just run the latest cached test run instead.

What do you think about that?

/cc @whatyouhide

**Comment by gausby** [comment]
Oh. I can actually get the behaviour I am asking for by running `C-c a r` (`alchemist-mix-rerun-last-test`). I didn't know that. That is great.

I guess changing the behaviour of run test cases to rerun last cached test would cause some confusion. How do I get back to running the entire test suit when I've run a focused test in a test file? I think `C-c a r`/`C-c a t` solves this problem. :)

**Comment by tonini** [comment]
@gausby Actually we wouldn't cache run whole test suite run. We just would run the cached `alchemist-mix-test-this-buffer` and `alchemist-mix-test-at-point` if we outside a test file and in the same mix project. Otherwise when we run `alchemist-mix-test` (the whole test suite) we wouldn't run any cached test at all.

**Comment by whatyouhide** [comment]
Hey there folks, sorry for the late response. I *constantly* use `SPC t r` which for me is bound to `alchemist-mix-rerun-last-test` which is an ABSOLUTELY GREAT FEATURE (I implemented it IIRC :monkey: :smile:). So my workflow is: I write a test, I run it (with the thing that runs the test at point, I don't remember the name) and then I go write the implementation and run `SPC t r` to rerun the test.

**Comment by tonini** [comment]
@whatyouhide @gausby I guess would could close this issue. The workflow which @whatyouhide explained is really nice and works well enough. :+1:

**Comment by gausby** [comment]
I have adopted the described workflow, so I am good. The «run at mark + run last test»-flow also work with quickcheck properties, so it is truly great.

Thanks @whatyouhide for implementing that.

**Comment by whatyouhide** [comment]
:tada:
