### ISSUE TITLE
Truncate lines by default on the test report buffer

### ISSUE THREAD

**Issue by davoclavo** [tonini/alchemist.el#186]
Running on `Alchemist 1.6.0`

The test report buffer does not truncate lines (word wrapping). Per recommendation from @tonini, running `toggle-truncate-lines` works, but I think this should be the default behavior, as it is very useful to debug why tests are failing.

**Comment by davoclavo** [comment]
Sorry, I got the term wrong. Currently, it truncates lines, but it should not truncate them.

**Comment by tonini** [comment]
@davoclavo Whats the status for you about this issue? 

The current behavior is that truncation is enabled, as you can see in the image below:

![truncation enabled](http://i.imgur.com/B7vGnPu.png)

And when we disable truncation like with `toggle-truncate-lines` (if you have truncation enabled by default) 

![truncation enabled](http://i.imgur.com/gCfNXaM.png)

/cc @gausby @whatyouhide what you guys think, whats your daily experience about that?

**Comment by gausby** [comment]
I actually [run `toggle-truncate-lines` when the test buffer opens](https://github.com/gausby/emacs.d/blob/master/setup/elixir-setup.el#L33), so I guess my vote is on this behaviour.

Would it make sense to do a keybinding for `toggle-truncate-lines` inside test buffers by pressing something like `T`, or would that diverge from the way other modes handle test buffers? Toggling them seems like a useful thing, especially when there are a ton of failing tests.

**Comment by tonini** [comment]
@gausby thats a great idea. :+1:  https://github.com/tonini/alchemist.el/blob/master/alchemist-test-mode.el#L112
