### ISSUE TITLE
Code.LoadError in Spacemacs

### ISSUE THREAD

**Issue by bordeltabernacle** [tonini/alchemist.el#187]
Not sure if this is an Alchemist problem or not.
I have a `word_count.exs` file and a `word_count_test.exs` file. Within the test file the exercise file is loaded:

```elixir
Code.load_file("exercise.exs")
```

To run this test file I would do `SPC m x f` and choose the file, no worries.

For some reason, today when I do it I get the following error:

```elixir
** (Code.LoadError) could not load /home/willem/code/exercism.io/word-count/word_count.exs
    (elixir) lib/code.ex:660: Code.find_file/2
    (elixir) lib/code.ex:319: Code.load_file/2
    code/exercism.io/elixir/word-count/word_count_test.exs:4: (file)
    (elixir) lib/code.ex:363: Code.require_file/2
```

My `.spacemacs` is [here](https://github.com/bordeltabernacle/dotfiles/blob/master/emacs/dotspacemacs)

**Comment by bordeltabernacle** [comment]
Actually, it looks like this is an Elixir issue as I get the same error when running the file in iex. Sorry.

**Comment by tonini** [comment]
Hi @bordeltabernacle 

I hope you found the issue. Thanks for reporting :)

Cheers

**Comment by bordeltabernacle** [comment]
hi @tonini, thanks.  It seems to have disappeared now, so I'm putting it down to the Linux Gremlins!

Alchemist is a beautiful thing btw, thankyou for building it. :+1:
