### ISSUE TITLE
How to turn the page of document buffer?

### ISSUE THREAD

**Issue by Cifer-Y** [tonini/alchemist.el#190]
for example the function: Kernel.SpecialForm.quote. It's doc is a very long page, how can I scroll the page down?
![emacs z local emacs today at 18 37](https://cloud.githubusercontent.com/assets/4470516/11469536/f97c5a42-9791-11e5-9c89-09608e66a2c7.png)

**Comment by tonini** [comment]
Hi @Cifer-Y 

I had a look at this case and searched through the Emacs documentation. 
There are two function which you can call to rather scroll down or up in the other window, in our case the window where the Elixir documentation for the current completion candidate is selected.

Here are an example where you can bind these two functions to two good reachable keybindings.

```lisp
(global-set-key (kbd "C-M-n") 'scroll-other-window)
(global-set-key (kbd "C-M-p") 'scroll-other-window-down)
```

`scroll-other-window` is for scrolling down in the next window.
`scroll-other-window-down` is for scrolling up in the next window. (Don't be confused by the `down` ;-)

So just give it a try and hit one of these functions when your on a selected candidate.

**Comment by Cifer-Y** [comment]
@tonini Thanks for your patience, I'm not very good at emacs, the two functions 'scroll-other-window and 'scroll-other-window-down is very helpful, thank you very much.

**Comment by tonini** [comment]
@Cifer-Y I'm glad that it helped. :+1:
