### ISSUE TITLE
Auto-reload current module in IEx

### ISSUE THREAD

**Issue by timbuchwaldt** [tonini/alchemist.el#192]
I was just playing around with the IEx integration and used the reload-feature IEx provides (`r(MyModule)`) and I wondered... wouldn't it be possible to reload the module in the current buffer directly via alchemist? So basically... detect if there is a module in the buffer, send it's name in a reload-command to the IEx, execute it.

**Comment by tonini** [comment]
@timbuchwaldt yes thats a good idea. I'll try to put it together later.

Thanks for the input :+1:

**Comment by timbuchwaldt** [comment]
Cool, looking forward to it! :)

**Comment by tonini** [comment]
Good morning @timbuchwaldt 

It's now available on the [master](https://github.com/tonini/alchemist.el/commit/395e671703252611fb9dc211d693bf5376090e9d)

You need to wait until [melpa](http://www.melpa.org) built the newest alchemist package from master. But after that you just can `M-x package-install` the newest version.

Thanks for the hint :+1:

**Comment by timbuchwaldt** [comment]
Mornin! :) It works, awesome - thanks for implementing that :)
