### ISSUE TITLE
Invoking and cancelling alchemist-mix makes tasks duplicated

### ISSUE THREAD

**Issue by goofansu** [tonini/alchemist.el#199]
I don't know whether this is a problem in alchemist.

I'm using [ivy-mode](https://github.com/abo-abo/swiper), which is a generic completion method for Emacs.

When `alchemist-mix` is invoked and canceled by `C-g`, every mix task will be duplicated, see the image below. If I execute a task, all duplicates will go away.

Don't know how to debug that, welcome to any help, thank you.

![duplicate items](http://i.imgur.com/3tS39j0.jpg)

**Comment by tonini** [comment]
Hi,

I have no idea about the reason why the mix tasks are duplicated, but I could try to fix it with a remove of duplication in the list before serving them.

Would you test a branch if I made one ready with a fix, because I can't reproduce it locally on my machine.

**Comment by goofansu** [comment]
@tonini sure

**Comment by tonini** [comment]
@goofansu Could you please update to the latest alchemist version and try this one again? It should be fixed by now.

Thanks

**Comment by goofansu** [comment]
Yes, fixed. Thank you.
