### ISSUE TITLE
Add version control

### ISSUE THREAD

**Issue by sandeshsoni** [tonini/alchemist.el#202]
Can we have layer version control added / enabled by default ?

So that one can directly jump to next hunk in file.
`SPC g . n` for next hunk
`SPC g . N` for previous hunk

My Alchemist version 1.7.0

**Comment by gausby** [comment]
Alchemist or Elixir mode does not handle source code version control, it seems like something specific to the Emacs VC package. May I suggest that you put it in an initialisation hook for emacs-mode if you want it activated by default for emacs-mode?

**Comment by syohex** [comment]
@sandeshsoni spacemacs ?

**Comment by tonini** [comment]
@sandeshsoni as @gausby already mentioned this has nothing to do with the purpuse of what Alchemist is for. 

I recommend you have a look at [magit](https://github.com/magit/magit) an awesome Emacs Git interface and much more. :+1:

**Comment by tonini** [comment]
I'll close this issue because it's about a topic which haven't to do with the purpose and functionality Alchemist is about.

Thanks
