### ISSUE TITLE
alchemist-project-toggle-file-and-tests and lib dir

### ISSUE THREAD

**Issue by aaronjensen** [tonini/alchemist.el#203]
When in a phoenix project, I have a `web` dir and a `lib` dir. I've preferred to keep my tests for lib within `test/lib` and tests for `web` simply within `test`. 

Unfortunately, alchemist assumes that anything in `lib` like `lib/foo.ex` wants its test to be in `test/foo.ex`. So, if I had `web/foo.ex` and `lib/foo.ex` they'd both end up in the same place in the test folder.

Would it be possible to make this configurable somehow? Thanks!

**Comment by aaronjensen** [comment]
Oh, and if there is already a convention for this and we're just "doing it wrong" that's fine too, we just don't know the convention.

**Comment by mosic** [comment]
Sorry if this is not constructive, but why would you have two files with the same name in `lib` and `web` directories? If they're both in the root of the two directories they would presumably also have the same module name, so you'd be basically redefining one module with another.

I think that having a `lib`or `web` directory inside `test` is unusual, you want to have something like this:
`lib/some_root_lib_module.ex`
`test/some_root_lib_module_test.exs`

`web/some_root_web_module.ex`
`test/some_root_web_module_test.exs`

`lib/my_app/some_other_module.ex`
`test/my_app/some_other_module_test.exs`

Take a look at these elixir applications for reference:
https://github.com/hexpm/hex_web
https://github.com/evercam/evercam-media

**Comment by aaronjensen** [comment]
@mosic yes, I'm trying this out now on my project. The way I was doing it is how rails did it, but I'm good w/ trying it this way for now. I'll close this out.
