### ISSUE TITLE
 Syntax-Highlighting and formatting for eex templates ?

### ISSUE THREAD

**Issue by rogergl** [tonini/alchemist.el#206]
It would be nice to have some Syntax-Highlighting and/or formatting.

For example

```
<%= if @changeset.action do %>
<div class="alert alert-danger">
  <p>Oops, something went wrong! Please check the errors below.</p>
</div>
<% end %>
```

could be formatted as:

```
<%= if @changeset.action do %>
   <div class="alert alert-danger">
       <p>Oops, something went wrong! Please check the errors below.</p>
   </div>
<% end %>
```

**Comment by gausby** [comment]
Hi @rogergl 

Alchemist doesn't handle indentation; indentation is handled by https://github.com/elixir-lang/emacs-elixir so I suggest opening the issue there. I don't know if it will handle Elixir specific indentation for eex templates; I have web-mode enabled in eex files, so I guess it is web-mode that handle the indentation :)

**Comment by tonini** [comment]
I'll close this issue because the syntax highlighting and indentation functionality is part of the `elixir-mode` as @gausby already mentioned.
