### ISSUE TITLE
Code style parsing via Dogma

### ISSUE THREAD

**Issue by achernyak** [tonini/alchemist.el#209]
I just came across a pretty nice Elixir package static code analytics. [Credo](https://github.com/rrrene/credo) parses your files for style issues. It seems to work great from my perspective.

Is there any possibility of integrating it with Alchemist as a linter?

**Comment by gausby** [comment]
Credo provides its own mix tasks, so you could execute it by running the `alchemist-mix` function, normally bound to <kbd>C-c a x</kbd> and select the credo task.

**Comment by achernyak** [comment]
That's actually my process right now.

I guess I wasn't very clear, but the idea would be to see this in the buffer you are current editing. Similar to how linters for other languages display directly on the line with the lint error.

**Comment by gausby** [comment]
Ah, I see. It is a nice idea, but my gut feeling is that it should go into a minor-mode of its own. My argument for this is that other linters might come around, and alchemist should not pick sides or play favourites with projects not in Elixir core.

I guess it could be achieved as a [flycheck](https://github.com/flycheck/flycheck) plugin. I'll investigate flycheck.

**Comment by gausby** [comment]
You can extend your alchemist setup like so:
```elisp
(defun mg/alchemist-run-credo-on-project ()
  "Run credo on project"
  (interactive)
  (alchemist-mix-execute "credo"))
(define-key alchemist-mode-keymap (kbd "p c") 'mg/alchemist-run-credo-on-project)
```
This will run credo on the project when `C-c a p c` is invoked.

**Comment by achernyak** [comment]
@gausby Thank you, that actually makes it much more pleasant to use. I just started using emacs a couple weeks ago, so this is really helpful.

**Comment by gausby** [comment]
Glad I could help, and I hope that you enjoy using Emacs

**Comment by walter** [comment]
Just a follow up note on "inline credo". Here's an example of what Atom looks like with it in place:

<img width="874" alt="screenshot 2016-10-21 09 40 27" src="https://cloud.githubusercontent.com/assets/10767/19822711/6f8df2b4-9dc1-11e6-9125-fc412947677e.png">
