### ISSUE TITLE
False autocomplete on whitespace input

### ISSUE THREAD

**Issue by lexmag** [tonini/alchemist.el#213]
For example in `config.exs` file, type `foo:` and move cursor to the beginning of the line type 2 spaces:

<img width="395" alt="screen shot 2016-03-19 at 18 51 05" src="https://cloud.githubusercontent.com/assets/248290/13900913/3563b7a4-ee12-11e5-9630-684472912ccc.png">

**Comment by tonini** [comment]
Hi @lexmag 

Thanks for the issue report, I found the problem and will push to master later on. :+1:

**Comment by lexmag** [comment]
Hey @tonini, that's great. :yellow_heart:

There is also some relevant problem I think:

<img width="420" alt="screen shot 2016-03-20 at 11 02 19" src="https://cloud.githubusercontent.com/assets/248290/13903855/6c7da334-ee8b-11e5-8c71-75c1c14c6494.png">

This is just typed as is, with no cursor movements.
