### ISSUE TITLE
Code formatting conflict with tab key

### ISSUE THREAD

**Issue by Korbin73** [tonini/alchemist.el#216]
First, thanks for building alchemist. It's fantastic. I do have a question about the code formatting. When I try to format code like this:
``` elixir
  begin_date =
      Timex.date(last_saved_read_date)
      |> Timex.shift(days: 1)
      |> Timex.to_erlang_datetime
      |> elem(0)
```

The indention doesn't work after starting the Timex.Date expression. The editor wants to put all subsequent lines (the ones starting with |> ) on the same indention level as begin_date. Is there something I'm doing wrong? I did try doing C-q tab. That did indent but once I moved the cursor to the next line it reformats it back.

**Comment by gausby** [comment]
As I read this question I figure it is about indentation—alchemist.el is all about tooling, such as integration with mix, jumping to definitions of things, all the stuff that makes you go wooh! Formatting and code highlighting are handled in and by another project: [the Elixir major mode](https://github.com/elixir-lang/emacs-elixir).

It is a known issue, and has been so for a while (sorry) https://github.com/elixir-lang/emacs-elixir/issues/243

**Comment by Korbin73** [comment]
Ahh. Yes, that's exactly what I was talking about. Hmm. Too bad I don't know emacs lisp. I would take a shot at doing a pull request if I did. Anyway thanks @gausby
