### ISSUE TITLE
Can not make code folding with alchemist.el.

### ISSUE THREAD

**Issue by flomop** [tonini/alchemist.el#217]
Are there any ways to make code folding in alchemist? Is this feature are going to be implemented?

**Comment by tonini** [comment]
Hi,

For code folding I recommend packages like
https://github.com/gregsexton/origami.el

flomop <notifications@github.com> schrieb am Do., 7. Apr. 2016, 00:56:

**Comment by flomop** [comment]
Hi, @tonini . Thanks for reply, origami is just perfect!

**Comment by gausby** [comment]
@flomop If you get it to work, and are willing to share your configuration for origami we/I can add it to the Alchemist documentation :)

**Comment by flomop** [comment]
@gausby Ok, I'll test it for at least few days and make feedback :)

**Comment by gausby** [comment]
@flomop if you create gist I can test along with you!

**Comment by flomop** [comment]
@gausby Since I'm using spacemacs, I created origami-layer and bind origami-toggle-node to tab-key.

https://gist.github.com/flomop/d2c328febbaf7ba74a7573b8ead22b13

**Comment by gausby** [comment]
@flomop I imagine we need an Elixir origami parser. I just installed origami and I am fairly sure it needs to be told what constitute a node, for Elixir I could imagine it would be `do..end` and `""".."""`.

**Comment by flomop** [comment]
@gausby I belief origami recognize node automatically using indentation. Since in my project I use a very strict indentation rules, I did not realize that you need to told origami about elixir-node delimiters.

**Comment by gausby** [comment]
@flomop Wow, that is true, it works as expected—I just needed to enable it in my Elixir buffers.

I'll try it out for a couple of days and see if it misbehaves. Thanks.
