### ISSUE TITLE
Running "Mix test this buffer" Appears Not To Run DocTests

### ISSUE THREAD

**Issue by OnorioCatenacci** [tonini/alchemist.el#219]
Hi Samuel,

Windows 10 
GNU Emacs 24.5.1 (i686-pc-mingw32).  
Alchemist 1.7.0 (package 20160322.251)
Elixir-Mode 2.2.8 (package 20160324.314)

When I run mix test from a command line, I get 5 doc tests run as expected:

> PS C:\Users\ocatenacci\pragmatic> mix test
> .....
> 
> Finished in 0.2 seconds (0.1s on load, 0.07s on tests)
> 5 tests, 0 failures

But when I run from within emacs via the Alchemist menu ("Mix test this buffer") it appears to not see the tests at all:

> Finished in 0.00 seconds (0.00s on load, 0.00s on tests)
> 0 tests, 0 failures
> 
> Randomized with seed 531000

Any ideas on what I might check to figure out what's going on?  It appears that mix is working but it just seems to miss all the tests.

**Comment by tonini** [comment]
Hi @OnorioCatenacci 

If you run `mix test this buffer` and you're not inside a `elixir test file` buffer nothing will run at all.

I guess you wanted to run the whole test suite like you explained you running outside emacs in the terminal.

I added the missing menu bar entry for running the whole test suite https://github.com/tonini/alchemist.el/commit/56f015e49ebc14e02e57db8da1be3dc9fa561e65

You just have wait until melpa.org build the latest alchemist.el package from the master.

Thanks for the report. :+1:

**Comment by OnorioCatenacci** [comment]
Ok, that makes sense. Thanks Samuel!
