### ISSUE TITLE
Cannot install Alchemist

### ISSUE THREAD

**Issue by expilo** [tonini/alchemist.el#222]
When I try to install Alchemist using M-x package-install on up-to-date Debian Jessie I am getting:

> package-compute-transaction: Package `elixir-mode-2.2.5' is unavailable

**Comment by tonini** [comment]
Hi @expilo 

Could you first try `M-x package-refresh-contents` and then `M-x package-install RET alchemist` again?

**Comment by expilo** [comment]
That did the trick. Thanks!

**Comment by whatyouhide** [comment]
@expilo you can close the issue if it's solved :)
