### ISSUE TITLE
alchemist-project-elixir-root is slow and called often

### ISSUE THREAD

**Issue by aaronjensen** [tonini/alchemist.el#224]
While trying to diagnose laggy typing in emacs, I discovered that the `alchemist-company` backend is responsible for creating lag:

Without:

![typing lag without alchemist-company](https://cloud.githubusercontent.com/assets/8588/14762206/be5095e6-0929-11e6-9172-f3dffcde1cd8.png)

With:

![typing lag with alchemist-company](https://screenshots-dx37.s3.amazonaws.com/monosnap/Typometer__Editor_latency_analyzer_2016-04-23_07-52-55.png)

Doing some profiling revealed that `alchemist-project-elixir-p` and therefore `alchemist-project-elixir-root` is responsible for much time:

![profile](https://screenshots-dx37.s3.amazonaws.com/monosnap/CPU-Profiler-Report_2016-04-23_075602_2016-04-23_07-57-03.png)

Stubbing out `alchemist-project-elixir-p` to just `t` yielded great results:

![typing lag with alchemist-project-elixir-p stubbed out](https://cloud.githubusercontent.com/assets/8588/14762218/0267fcf6-092a-11e6-9454-b527b013cfa3.png)

Could `alchemist-project-elixir-p` or maybe even `alchemist-project-elixir-root` be memoized?

**Edit:** I realize now I should have stubbed it to nil, since I was in a project. Doing so yields not quite as good a results, for apparently a similar reason. `alchemist-project-root` is also slow and should probably be memoized as well:

![typometer editor latency analyzer 2016-04-23 08-18-56](https://cloud.githubusercontent.com/assets/8588/14762304/08d154a0-092c-11e6-9433-b1fc74ab68ca.png)

![cpu-profiler-report 2016-04-23 08 17 33 2016-04-23 08-19-09](https://cloud.githubusercontent.com/assets/8588/14762305/1485f9d6-092c-11e6-941f-2074e8c8e607.png)

**Comment by tonini** [comment]
Thanks @aaronjensen for the great informative overview.

We could/should cache the function for sure. 👍

**Comment by tonini** [comment]
@aaronjensen could you run your diagnose test with the following branch? https://github.com/tonini/alchemist.el/pull/225

**Comment by aaronjensen** [comment]
@tonini not much improvement:

![typometer editor latency analyzer 2016-04-25 07-55-05](https://cloud.githubusercontent.com/assets/8588/14788041/07bd3fb2-0abb-11e6-86b3-6174d696dc02.png)

```
- let*                                                           7031  53%
 - if                                                            7031  53%
  - alchemist-project-elixir-root                                7031  53%
   - cond                                                        6833  52%
    - let*                                                       6833  52%
     - if                                                        6833  52%
      - alchemist-project-elixir-root                            6833  52%
       - cond                                                    6281  47%
        - let*                                                   6281  47%
         - if                                                    6281  47%
          - alchemist-project-elixir-root                        6281  47%
           - cond                                                5937  45%
            - let*                                               5937  45%
             - if                                                5937  45%
              - alchemist-project-elixir-root                    5937  45%
                 cond                                            5232  39%
                 stringp                                          705   5%
           + stringp                                              344   2%
       + stringp                                                  552   4%
   + stringp                                                      198   1%
+ sp--looking-back                                               3935  29%
+ apply                                                           792   6%
+ sp-delete-pair                                                  233   1%
+ spaceline--segment-persp-name                                   169   1%
+ sp--looking-back-p                                              166   1%
+ ucs-normalize-HFS-NFC-region                                    141   1%
  Automatic GC                                                    128   0%
+ syntax-ppss                                                      48   0%
+ spaceline--eval-segment                                          38   0%
+ sp--looking-at                                                   37   0%
+ ucs-normalize-region                                             28   0%
```

**Comment by aaronjensen** [comment]
Ah, actually, that makes sense because I did not open anything in the elixir source, so that cache would never be set. Also, my project would never trigger that. So I think it may require a per-path cache or maybe buffer local (not sure how you'd reset it in the pathological case of moving a project file into the elixir root)

**Comment by tonini** [comment]
I see the problem with the elixir source path cache. But I guess we got the solution by free with the `alchemist-goto-elixir-source-dir` variable (which is used by `alchemist-goto`). What do you think?

**Comment by tonini** [comment]
@aaronjensen Ok I updated the branch, if you get the time please give it another try :)

Be sure you initialized the variable `alchemist-goto-elixir-source-dir` like explained here http://alchemist.readthedocs.org/en/latest/basic_usage/#definition-lookup

**Comment by aaronjensen** [comment]
Looks much better! I tested on a different computer and I don't have the results here but it was a smoother line, and the profile looked like it wasn't alchemist related, so 👍

**Comment by tonini** [comment]
Many thanks @aaronjensen for benchmarking this case and helping fixing it. 👍 

I'll close it now because #225 is merged into master.

💛 💙 💚 ❤️
