### ISSUE TITLE
Improve recompilation

### ISSUE THREAD

**Issue by aaronjensen** [tonini/alchemist.el#228]
At the moment, the best way to recompile a given file into your alchemist iex session is `alchemist-iex-compile-this-buffer`, which works, but leaves `.beam` files in your current working directory. `IEx.Helpers.c/2` takes a path, so I assume we could specify the existing build path if there is one. I do not know how to find that or detect that we are within a mix project.

Alternatively, or perhaps additionally, an easy `recompile/0` hook would be nice so that after making a change I could force a recompile for my mix project.

Even more fancy would be automatic detection of writes to files and automatic recompilation, though this can perhaps be [handled](http://stackoverflow.com/questions/32540703/make-elixir-app-recompile-and-reload-on-source-code-change) by things like [sync](https://github.com/rustyio/sync) and [remix](https://github.com/AgilionApps/remix)

**Comment by tonini** [comment]
Thanks @aaronjensen 

I'll work on this one and let you know about in the PR.
