### ISSUE TITLE
I can't get to see the completion for the code of my project

### ISSUE THREAD

**Issue by parkouss** [tonini/alchemist.el#230]
Though it is working for base elixir code. I narrowed down the bug to one function in the server file, I'll attach a PR.

**Comment by parkouss** [comment]
So, with this patch it works fine for me. Please let me know what you think, and thanks a lot for this great package!

**Comment by parkouss** [comment]
BTW, I use emacs 24.5.1.

**Comment by epogue** [comment]
I'm running into the same problem. It is also affecting my ability to use commands like `alchemist-mix`. `alchemist-server-status` always responds with `alchemist-server` as the current project even though I am definitely working inside of a `mix` project. Currently using emacs HEAD (25.1.50).

**Comment by parkouss** [comment]
Oh, got it. The default value of alchemist-goto-elixir-source-dir is "", and this makes the function alchemist-project-elixir-root returns "", and then alchemist-project-elixir-p finally returns t...

So we end up with the server thinking that we are in the elixir source code. :(

So, I am not sure if it is a bug (it may be on purpose, but in that case it would be great to say in the documentation that it is required to provide this variable).

Else, maybe that can be fixed using a default value of nil for the declaration of alchemist-goto-elixir-source-dir ? It is declared as a string type (https://github.com/parkouss/alchemist.el/blob/master/alchemist-goto.el#L47-L50) I don't know if we can safely set it to nil. A last solution may to add a special case in alchemist-project-elixir-root.

@tonini I would be happy to modify my PR to fix that if you think it should be fixed. Do you have any preference on how to fix that in that case?

**Comment by tonini** [comment]
@parkouss thats a great catch! 

It would't be great if you could modify the PR that it would use the `alchemist-utils-empty-string-p` to check `alchemist-goto-elixir-source-dir` inside `alchemist-project-elixir-root`.

This should work then.

**Comment by parkouss** [comment]
@tonini done. :) I tested it a bit, this seems to works fine.

**Comment by epogue** [comment]
:+1: Thanks @parkouss!
