### ISSUE TITLE
iex repl position

### ISSUE THREAD

**Issue by NgaNguyenDuy** [tonini/alchemist.el#232]
Hi,

When i start iex repl by command `alchemist-iex-run`, the repl is located at the right. I used popwin to put it to the bottom but it's not work.
Here is the code:

```elisp
(use-package popwin
  :ensure popwin
  :config (progn
            (popwin-mode 1)
            (push '(Alchemist-IEx :position bottom) popwin:special-display-config)))
```

Pls help me.

**Comment by gausby** [comment]
It has been a while since I used popwin (switched to schakle a while back), but try renaming `Alchemist-IEx` to `"*Alchemist-IEx*"`.

**Comment by NgaNguyenDuy** [comment]
Thank @gausby . It's worked. :+1:
