### ISSUE TITLE
Alchemist hex functions seem to return `search failed` 

### ISSUE THREAD

**Issue by gausby** [tonini/alchemist.el#236]
When executing `alchemist-hex-releases` and typing in a module it will fail with the following message:
```
save-current-buffer: Search failed: "

"
```
This seems to be the case for `alchemist-hex-info`, `alchemist-hex-search`, etc.

**Comment by tonini** [comment]
Thanks for the report @gausby :+1:

**Comment by tonini** [comment]
Hi @gausby 

The issue should be fixed on https://github.com/tonini/alchemist.el/commit/52037e881970d4cc3eebbad560b8312384ac3bbb

As always thanks for your patience 💚 💛 💙 😄
