### ISSUE TITLE
Unable to jump to definitions in stdlib

### ISSUE THREAD

**Issue by shosti** [tonini/alchemist.el#241]
This might be setup-specific (I'm using [asdf](https://github.com/asdf-vm/asdf) for elixir version-management), but jumping to definitions in Elixir/the stdlib doesn't work out of the box on my system. A little poking makes it easy to see why:

```
~/src/elixir/meta $ elixir ~/src/elixir/alchemist-server/run.exs --env=dev --listen
ok|localhost:44205
```
```
~ $ nc localhost 44205
DEFL  { "List,flatten", [ context: Elixir, imports: [], aliases: [] ] }
/Users/jose/OSS/elixir/lib/elixir/lib/list.ex
END-OF-DEFL
```
Obviously not much good :wink:

As a horrifically hacky workaround, I've symlinked /Users/jose/OSS/elixir to a local checkout of the elixir source code, which seems to work pretty well.

 I'm wondering if you have thoughts on a better solution? (Ideally this would be fixed upstream, but I'm not sure how feasible that is.) One idea: have an `alchemist-elixir-src-dir` variable that's user-settable and gets passed into alchemist-server as a default (kind of analogous to `find-function-C-source-directory`).

**Comment by tonini** [comment]
Hi @shosti 

I guess you just need to setup the right erlang & elixir source variables. Have a look here how to do this: http://alchemist.readthedocs.io/en/latest/basic_usage/#definition-lookup

Please give me feedback or ping me #irc or #slack if you still have issues.

**Comment by tonini** [comment]
ping @shosti

**Comment by tonini** [comment]
@shosti ping :)

**Comment by shosti** [comment]
@tonini sorry got sidetracked! Those both look perfect; couldn't find them earlier. I'll give them a try!
