### ISSUE TITLE
Jump to definition sometimes not working on with new alias syntax

### ISSUE THREAD

**Issue by gstamp** [tonini/alchemist.el#242]
The new alias syntax seems to cause problems with alchemist jump to definition.

```
alias Bob
alias Foo.{Bar, Baz}
```

If I change things to

```
alias Foo.{Bar, Baz}
alias Bob
```

Things seem to work as expected so it appears to be related to the ordering.

**Comment by tonini** [comment]
Thanks for the report on this one @gstamp, I'll have a look at this asap.

**Comment by tonini** [comment]
It's fixed on https://github.com/tonini/alchemist.el/commit/6863032d8377bc4f116e145ab9bf02b2143acbfc

Thanks for the report
