### ISSUE TITLE
Company backend ’alchemist-company’ should not be added globally.

### ISSUE THREAD

**Issue by stardiviner** [tonini/alchemist.el#244]
Most user add `company-yasnippet` by define their own global `company-backends`.
I think `alchemist-company` should not be added to global backends list by default in the package.

And also added in the global list will cause warning message like:
```
Company backend ’alchemist-company’ could not be initialized:
```
When I opened org agenda buffer.

**Comment by Trevoke** [comment]
The company backend for Golang shows how we can do it ourselves, so I'm guessing similar changes can be applied inside alchemist:

https://github.com/nsf/gocode/tree/master/emacs-company

**Comment by stardiviner** [comment]
I created an PR:
https://github.com/tonini/alchemist.el/pull/248
