### ISSUE TITLE
This project violates emacs' key binding conventions

### ISSUE THREAD

**Issue by NobbZ** [tonini/alchemist.el#246]
The conventions can be read in full here: https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html

To be exact, it does violate this rule:

> *  Don’t define C-c letter as a key in Lisp programs. Sequences consisting of C-c and a letter (either upper or lower case) are reserved for users; they are the only sequences reserved for users, so do not block them.
>  
>   Changing all the Emacs major modes to respect this convention was a lot of work; abandoning this convention would make that work go to waste, and inconvenience users. Please comply with it.

Currently, I do not use `C-c a` for anything, but other people might do. Also I planned to use it as a prefix for my emacs integrated **a**pplications (mail, usenet, etc).

**Comment by gausby** [comment]
Thanks for reporting this; there is already an open issue on this: #229

**Comment by NobbZ** [comment]
Oh, sorry, I haven't seen that. I'll close this one here then.
