### ISSUE TITLE
Let `truncate-lines` be customizable 

### ISSUE THREAD

**Issue by gabrielelana** [tonini/alchemist.el#249]
Running on Alchemist `1.8.0`

Usually I open the alchemist buffers (especially the test report) side by side to my code, when I have errors the default line truncation is really annoying because I need to jump to the window and press `t`. I tried to overcome the problem (following the advice from #186)

``` elisp
(add-hook 'alchemist-test-report-mode-hook
              (lambda ()
                (with-current-buffer (get-buffer "*alchemist test report*")
                  (setq-local truncate-lines nil))))
```

But without success, I think that your code executes after the hook, you could avoid that running hooks explicitly when you define the major mode

``` elisp
(define-derived-mode alchemist-test-report-mode fundamental-mode "Alchemist Test Report"
  ; ...
  (run-hooks 'alchemist-test-report-mode-hook)
  ; ...
  )
```

Or, better, you can make that configurable, since all the alchemist buffers are truncated and not all have a major mode to hook in

If you don't have time I can try to create a PR to make the truncation configurable

**Comment by mosic** [comment]
Just chiming in to say that I'd also appreciate this feature. I also tried using a hook but it didn't work.

**Comment by jhonathas** [comment]
@gabrielelana 

I know this issue is old, but I still can not do automatic truncation. You can? If so, did you set it up?
