### ISSUE TITLE
Feature request - Add syntax highlighting and indentation support for the `with` statement

### ISSUE THREAD

**Issue by evanson** [tonini/alchemist.el#253]
Here's a description of how the `with` statement is used: http://elixir-lang.org/docs/master/elixir/Kernel.SpecialForms.html#with/1

**Comment by syohex** [comment]
Is this [elixir-mode](https://github.com/elixir-lang/emacs-elixir) issue ?

**Comment by tonini** [comment]
@evanson yes, @syohex is right. Things about indentation and highlighting belongs to the `elixir-mode`.

**Comment by evanson** [comment]
Ah, right.

**Comment by syohex** [comment]
BTW It looks elixir-mode already supports `with` statement highlighting and indentation.
