### ISSUE TITLE
Can not jump to definition in other files when compiling in a docker container.

### ISSUE THREAD

**Issue by sdwolf** [tonini/alchemist.el#255]
OS: `Manjaro Linux v230`
Elixir: `1.3.2`
Erlang: `19`
Emacs: `24.5.1`
Alchemist: `1.8.1 (package 20160921.499)`

I am using spacemacs as following:

```
curl -fSLo ~/.spacemacs \
  https://raw.githubusercontent.com/sdwolf/dotfiles/master/.spacemacs

git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

git clone https://github.com/sdwolf/spacemacs-xclip.git ~/.emacs.d/private/xclip
```

The project I am trying to navigate is: `https://github.com/sdwolf/exlearn`

I can jump to functions defined in the current file and to functions from the elixir/otp sources but not to the ones in other files defined in my project.

Setting `(setq debug-on-error t)` gives the following error:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-exists-p(nil)
  #[257 "\303!\203\304\305\300\"\207\306!\203\307\301\302#\207\310!\2033\311!\306!\203.\307\301\302#\2022\304\305\300\"\207\312!\203`\313!\314!\306!\203M\307\301\302#\202_\306!\203[\307\301\302#\202_\304\305\300\"\207\315 \210\304\305\300\"\207" ["Forwarder.forward_for_test" "Forwarder" "forward_for_test" alchemist-utils-empty-string-p message "Don't know how to find: %s" file-exists-p alchemist-goto--open-file alchemist-goto-elixir-file-p alchemist-goto--build-elixir-ex-core-file alchemist-goto-erlang-file-p alchemist-goto--build-elixir-erl-core-file alchemist-goto--build-erlang-core-file pop-tag-mark] 7 "\n\n(fn FILE)"]("/work/lib/exlearn/neural_network/forwarder.ex")
  #[0 "\304\300\nB\305\300!\205\306\n!\211\304!\266\202)\207" ["/work/lib/exlearn/neural_network/forwarder.ex\nEND-OF-DEFL\n" inhibit-quit alchemist-goto-filter-output alchemist-goto-callback nil alchemist-server-contains-end-marker-p alchemist-server-prepare-filter-output] 4 "\n\n(fn)"]()
  funcall(#[0 "\304\300\nB\305\300!\205\306\n!\211\304!\266\202)\207" ["/work/lib/exlearn/neural_network/forwarder.ex\nEND-OF-DEFL\n" inhibit-quit alchemist-goto-filter-output alchemist-goto-callback nil alchemist-server-contains-end-marker-p alchemist-server-prepare-filter-output] 4 "\n\n(fn)"])
  alchemist-goto-filter(#<process /home/sdwolf/Projects/exlearn/> "/work/lib/exlearn/neural_network/forwarder.ex\nEND-OF-DEFL\n")
```

This error seems to be caused by the fact that the project was compiled inside a docker container, where the project path is `/work` instead of `/home/sdwolf/Projects/exlearn`. After I compiled it on the host it works as expected.

Not sure if this is something you can/should fix. Thoughts?

**Comment by tonini** [comment]
@sdwolf Hi

>> This error seems to be caused by the fact that the project was compiled inside a docker container, where the project path is /work instead of /home/sdwolf/Projects/exlearn. After I compiled it on the host it works as expected.

Yes that is the issue, you need to understand that the `alchemist-server` gets the informations about completion/src from the `BEAM` files, which lay in the project root directory (`_build/...`).

**Comment by sdwolf** [comment]
I've worked around this by moving my emacs inside a container with the same setup as the one in which i compile.

Is it OK if I create a PR to highlight this behavior in the auto-completion section of the docs?
