### ISSUE TITLE
Weird character when entering heredoc

### ISSUE THREAD

**Issue by tjgillies** [tonini/alchemist.el#265]
I'll enter `"""` on one line and then the next time I try to enter `"""` it's inserting a `\` so that it becomes `""\"`. Am I missing something?

**Comment by tonini** [comment]
Hi, that sounds like not an `Alchemist` issue. Instead have a look at autopair packages which you using like `smartparens` etc.

**Comment by tjgillies** [comment]
Ah that was it! Thanks!
