### ISSUE TITLE
Can it lint my elixir code on the fly or on the save?

### ISSUE THREAD

**Issue by collegeimprovements** [tonini/alchemist.el#273]
Hi I'm using `spacemacs`. I've installed `credo` and `bunt` as shown in [the guide](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/elixir). Even though I'm not able to see any effect when I make some mistake like writing `IO.pust` instead of `IO.puts` or when indentation is wrong or when I try to use some undefined module(e.g. `ThisModuleDoesNotExist.imaginary_method`) in an elixir file!!

Is it possible ? If yes, how can I do it? 
Sorry for my naivete.

Thanks a lot.

**Comment by syohex** [comment]
It can lint by flycheck. Do you enable flycheck-mode(`global-flycheck-mode`) ? flycheck setting is in [the guide](https://github.com/syl20bnr/spacemacs/tree/master/layers/+lang/elixir). Please check it.

**Comment by collegeimprovements** [comment]
Yes. I've done it. But it doesn't suggest any hint/error when I give some NonExisistentModuleName or use some method on a module that is not defined. Is it possible to lint this type of error/gotchas with flycheck and alchemist?

**Comment by axelson** [comment]
For Spacemacs you should check out the layer docs:
https://githuba.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/elixir#flycheck
