### ISSUE TITLE
Keyword (if) inside of a comment still triggers code completion

### ISSUE THREAD

**Issue by x-ji** [tonini/alchemist.el#294]
Steps to reproduce:

1. In a buffer with Elixir major mode activated, open a line of comment starting with `#`
2. Type `if`
3. Type space

Expected behavior: The space is normally inserted and nothing happens

Actual behavior: Code completion is triggered. `do` is inserted on this line and `end` is inserted on the next line.

Alchemist version: 1.9.0snapshot (package: 20170118.142)

Not sure if this is a bug in alchemist or if it has been dealt with already, but my cursory search among the issues doesn't seem to turn up a similar issue...

**Comment by x-ji** [comment]
OK, seems that it's actually a behavior of smartparens instead of alchemist? From https://github.com/tonini/alchemist.el/issues/276

**Comment by tonini** [comment]
Thanks
