### ISSUE TITLE
mix credo => No match (alchemist 1.9.0snapshot)

### ISSUE THREAD

**Issue by bsmr** [tonini/alchemist.el#295]
Maybe I am doing it the wrong way (I want to _explicitly_ run `mix credo`), but when I try `C-c a x credo` I get a `[No match]`.

A `C-c a x help` shows that credo is available.

_Note:_ Actually I could invoke `C-c a x credo` *once*, but currently I cannot reproduce it. Happily trying it another time again resulted in a `[No match]` result.

**Comment by tonini** [comment]
Hi @bsmr 

Could it be that something with your emacs and environment setup is not correct?

Because all what `alchemist` does is call that mix task via emacs functionality and runs it. 

I think emacs calls the wrong mix version.

**Comment by bsmr** [comment]
Almost _impossible_ because there is only one `mix` available.
But I will have a closer look at it (hopefully at the weekend).

**Comment by bsmr** [comment]
Finally I had time to finish the setup of my development system for some tests.

The bad thing: now, it is somewhat different to the one, when I reported the _issue_.

| Software | Old | Now |
| --- | --- | --- |
| OS          | Ubuntu 16.10 | Debian 8.8 |
| Emacs    | 24.5/25.1 | 25.2 |
| Erlang     | <19.3 | 19.3.5 |
| Elixir        | <1.4.3 | 1.4.4 |
| Alchemist | 1.9.0 | 1.8.2 |
| Credo      | <0.7 |  0.8 |

Also my current `init.el` is very basic, compared to my _old_ one.

The good part is, that currently I can not reproduce the reported problem, e.g. **it works**.
