### ISSUE TITLE
Link to site (http://www.alchemist-elixir.org) does not work

### ISSUE THREAD

**Issue by maxbendick** [tonini/alchemist.el#299]
Chrome says "www.alchemist-elixir.org’s server DNS address could not be found" when I try to follow the link to the site (http://www.alchemist-elixir.org).

**Comment by tonini** [comment]
Hi @maxbendick 
Thanks for the report about that, I reliazed that dnsimple now have a subscription plan way of doing things. I should work now again.

Thanks :heart: :green_heart: :blue_heart:

**Comment by maxbendick** [comment]
Thank you!
