### ISSUE TITLE
alchemist-utils-empty-string-p: Symbol’s function definition is void: s-trim

### ISSUE THREAD

**Issue by BlindingDark** [tonini/alchemist.el#307]
Emacs For Mac OS X 25.2
MacOS 10.12.5
MELPA Stable, alchemist 1.8.2

Trying to use company, As I type, I see

```
error in process filter: alchemist-utils-empty-string-p: Symbol’s function definition is void: s-trim
```

#105 This issue similar to my situation

I try to install alchemist manually (latest version from master branch).
When I try again, It told me, execute `(require 's)` failed
So I try to install `s.el`

```
M-x package-install [RET] s [RET]
```

And restart Emacs... It worked!

But when I try to install alchemist with `package-install` again, It still not work, same error message, even I already installed `s.el`.

Is this caused by Emacs For Mac OS X?

**Comment by BlindingDark** [comment]
When I put (require 's) in .emacs, It worked!

**Comment by tonini** [comment]
Hi @BlindingDark 
Thanks for the report, although the issue you have is already fixed. But as I can see you using MELPA Stable and the fix isn't released in a patch or minor release so far. You just need to use it to install it via MELPA and not MELPA Stable.
I hope to bring Alchemist v1.8.3 soon.

Thanks
