### ISSUE TITLE
Is documentation inside IEx buffer broken?

### ISSUE THREAD

**Issue by avli** [tonini/alchemist.el#31]
Company mode is active and completion works fine, but I don't see documentation for selected functions like shown in "Complete & Documentation lookup" paragraph. I use alchemist version 20150107.2241 and Elixir 1.0.2. Am I doing something wrong?

**Comment by tonini** [comment]
Hi @avli 

When a candidate is selected in the completion list, you need to hit the key <kbd>C-d</kbd> to open the proper documentation. Did you did that?

**Comment by avli** [comment]
Hi @tonini 

Silly me :) You're right, I didn't press `C-d`. Now I see `C-d` chord is mentioned in "Auto-completion" section. Probably it will be a good idea to repeat this information one more time in "Complete & Documentation lookup" section for those like me :)

**Comment by tonini** [comment]
Glade you found it. :-)

Yeah I need to refine the whole README. ;-)

**Comment by avli** [comment]
Thank you! I think the issue can be closed.
