### ISSUE TITLE
insert 'end' when typing 'do' occurs in invalid contexts such as in comments

### ISSUE THREAD

**Issue by jasongoodwin** [tonini/alchemist.el#330]
if you type 'do' in a comment, 'end' is automatically inserted.
For "" and "" and () and {} this is reasonable behaviour but not the words :(

**Comment by jasongoodwin** [comment]
same with typing `if` - it causes a `do` to appear in comments.

**Comment by gausby** [comment]
…are you by any chance a "Spacemacs" user?

**Comment by jasongoodwin** [comment]
Hey yes I am. Is this a problem with spacemacs??

**Comment by gausby** [comment]
I am fairly sure it is. They have a history of adding "improvements" without actually testing it, resulting in a ton of bug reports. Generally I suggest people rolling their own Emacs config :)

It could perhaps be an issue with the smartparens package, or the spacemacs config of it.

**Comment by bitwalker** [comment]
This is fixed in the latest smartparens release, I reported it [here](https://github.com/Fuco1/smartparens/issues/877) and it was very promptly fixed :). I think this can be closed!
