### ISSUE TITLE
Document look up doesn't work with local function

### ISSUE THREAD

**Issue by fremontmj** [tonini/alchemist.el#34]
When I run alchemist-help-search-at-point on this line:
Riffer4.testMike

I get a documentation window.  

When I run it on a line within the same module with just:
testMike 
I don't get a documentation window; instead I get "error in process sentinel: Wrong type argument: stringp, nil.

**Comment by tonini** [comment]
@fremontmj you can't run documentation lookup for a function without the Module information. Except for example Kernel functions.

You can test this in `iex` itself. Thats not an Alchemist thing, thats how Elixir works and needs to know the Module information too.

But the error message by Alchemist is not good, thanks you reported this I will fix this.

Cheers

**Comment by tonini** [comment]
The fix with the message is merged. https://github.com/tonini/alchemist.el/commit/aa6249c39d22e36c8f14e022b470c43950abbd0a?diff=unified#diff-9137299d451394ff8675817a3621bd62R97

It's on master, but you have to wait until MELPA built the package. Or you just use it manually.

**Comment by fremontmj** [comment]
Oops, I see what you mean about needing the Module name.

Thanks!
