### ISSUE TITLE
Don't open new window for tests if *mix* window already exists in another frame (enhancement)

### ISSUE THREAD

**Issue by fremontmj** [tonini/alchemist.el#36]
Alchemist reuses the *mix* buffer if it's in the same frame as the cursor, but if you have a *mix* buffer in another frame, it opens a new one in the current frame, and then the output is shown in both frames.

It would be better if Alchemist could notice if the buffer already exists in *any* frame, and just reuse that one.

**Comment by rranelli** [comment]
You can setup this yourself with

```elisp
(setq-default display-buffer-reuse-frames t)
```

This will achieve what you want ;). I use this to keep a frame dedicated to the compilation buffer.

**Comment by rranelli** [comment]
@fremontmj, were you able to solve your issue with my suggestion?

Can this issue be closed?

Thanks !

**Comment by fremontmj** [comment]
Sorry, I've been away awhile.  This indeed works, thanks, and the issue can be closed!

Best,

Mike
