### ISSUE TITLE
Goto not working when jumping to the same file

### ISSUE THREAD

**Issue by X4lldux** [tonini/alchemist.el#38]
When jumping to a function that is in current buffer nothing happens.
Removing `save-excursion` from `alchemist-goto-definition-at-point` solves the problem - I think it shouldn't be in a function which supposed to move the point.

**Comment by tonini** [comment]
Thanks for reporting, I will push a fix asap. <3

X4lldux <notifications@github.com> schrieb am Do., 15. Jan. 2015 23:07:
