### ISSUE TITLE
Help fails with error

### ISSUE THREAD

**Issue by edubkendo** [tonini/alchemist.el#41]
When I try to use the `help` function  (specifically, `alchemist-help-search-at-point`) I get the error:

`error in process sentinel: Wrong type argument: stringp, nil`

I'm using evil-mode so it's possible that is where the problem is. I am not sure how long since it stopped working.

**Comment by tonini** [comment]
Hey @edubkendo 

I tried it on `master` and its working so far.

Could you tell me in which situation on what expression you used it when getting the message?

**Comment by edubkendo** [comment]
@tonini a little more experimenting makes it seem to be an issue related to `helm`. If I go to this line: https://github.com/edubkendo/test_alchemist/blob/master/lib/test_alchemist.ex#L4 (repo I made for this case, nothing special) and type `:` (this is basically the evil-mode equivalent of M-x) and then type `alc` and tab, this brings up helm which then lets me fuzzy match for `alchemist-help-search-at-point` which then returns with the error.  I also tried the following and got the same error: exit evil-mode into emacs-mode, type `M-x helm-M-x` then repeat the same process. It gives me the error. I am thinking that something about the interaction with helm prevents it from grabbing the text from the buffer maybe?

I seem to be able to get docs by either typing out the full `alchemist-help-search-at-point` without using helm, or by using the plain `alchemist-help` and navigating to what I'm looking for.

**Comment by tonini** [comment]
This is hard to say, because I have no idea about helm and how it calls functions. Maybe there is an issue with the expression crapping under the cursor when the function is called over helm. 

Would be great if someone who's use helm and also have some lisp knowledge could have a look at it.

**Comment by edubkendo** [comment]
Yeah, I can work around it ok enough for now. Just wanted to report it for the record.

**Comment by tonini** [comment]
Yeah thanks a lot :) maybe use the keybinding? Or help me find a new way of
shorter key bindings :-)

Eric West <notifications@github.com> schrieb am Fr., 16. Jan. 2015 15:32:

**Comment by tonini** [comment]
@edubkendo whats the status about the usage of `alchemist-help-search-at-point` via `helm`, do you still getting the error `error in process sentinel: Wrong type argument: stringp, nil`?

**Comment by edubkendo** [comment]
I am, just updated to latest alchemist and gave it a try :(

**Comment by tonini** [comment]
Thanks @edubkendo ! I guess I need to install `helm` and try to find this bug :)

**Comment by tonini** [comment]
@edubkendo hey :)

I'm not sure if the Alchemist v1.0 released fixed this problem, but could you please give it a try?

**Comment by edubkendo** [comment]
seems to be working now, awesome!

**Comment by tonini** [comment]
Great! Thanks for testing it! <3
