### ISSUE TITLE
Discuss: ctags

### ISSUE THREAD

**Issue by X4lldux** [tonini/alchemist.el#43]
Does using ctags ([mmorearty/elixir-ctags](https://github.com/mmorearty/elixir-ctags), [rgrinberg/mix_ctags](https://github.com/rgrinberg/mix_ctags)) can enhance in any way alchemist?

**Comment by tonini** [comment]
@X4lldux Alchemist has a functionality to jump to module/function definition and it does that differently than `ctags`. It reads the source of the compilation file straight from Elixir source code.

`ctags` is different, its like scanning the Elixir source and build a tags file which holds the informations about the defintions.

Alchemist uses the `M-.` and `M-,` for jump to definition and jump back. So if you want to use `ctags` combined with Alchemist, you need to rebind `ctags` keybindings by yourself.
