### ISSUE TITLE
Setting the mix env

### ISSUE THREAD

**Issue by jtmoulia** [tonini/alchemist.el#45]
Pretty straightforward: I'd love to be able to set the `MIX_ENV` for the various alchemist mix commands, e.g. `alchemist-mix-compile`. Having to switch constantly switch environment with `getenv`/`setenv` is tiring and error prone. 

Maybe it could be implemented as a prefix arg to the mix commands?

btw, I've only been using alchemist for a couple of weeks, but it's already saved me a ton of time -- thanks!!

**Comment by tonini** [comment]
@jtmoulia Thanks a really great idea. 

I will try to implement this soon.

Cheers

Sam
