### ISSUE TITLE
Completion fails in nested project having its own dependencies

### ISSUE THREAD

**Issue by wrachwal** [tonini/alchemist.el#46]
If a nested mix project defines its own dependencies, mix tool keep them in deps/ in the root directory of the whole project. This is right and desired behavior. Unfortunately, this fools Alchemist which pops up:

```text
== ALCHEMIST COMPLETION FAILED ==
== OUTPUT BEGIN:
Unchecked dependencies for environment dev:
* asn1ex (https://github.com/vicentfg/asn1ex.git)
  the dependency is not available, run `mix deps.get`
** (Mix) Can't continue due to errors on dependencies
== OUTPUT END:
```

When I did deps.get immediately in the nested project, I get another error:

```text
== ALCHEMIST COMPLETION FAILED ==
== OUTPUT BEGIN:
** (Mix) Could not start application lte_rrc: could not find application file: lte_rrc.app
== OUTPUT END:
```

I guess it can be related with the fact that in Emacs by default CWD is where a visited file resides, not where emacs process was started, a fortiori where root of a whole Elixir project is.

Obviously, whatever completions are provided by standard Elixir shell (`iex -S mix`) started in the root, works as expected, e.g. `:lte_rrc.<TAB>` list all exported functions.

**Comment by tonini** [comment]
@wrachwal Sorry for the late answer, I have a lot of work at the moment but I will have a look into it soon.

Cheers

Sam

**Comment by tonini** [comment]
@wrachwal Alchemist v1.0 is released and this issue should be fixed with it. Could you please test this case and then close the issue?

**Comment by tonini** [comment]
I close this issue because v1.0 is released and this kind of bugs can't happen anymore. 

Thanks
