### ISSUE TITLE
emacs-elixir and alchemist.el

### ISSUE THREAD

**Issue by andreas-roehler** [tonini/alchemist.el#54]
Thanks a lot writing that marvellous stuff. Is it going to be backported to emacs-elixir?
Alchemist seems to take the menu of elixir-mode. Maybe not define as own (minor)-mode, just loading the stuff as extension?

**Comment by tonini** [comment]
@andreas-roehler the idea of alchemist is to integrate all the tool chain which comes from Elixir. Emacs-Elxir provides font-locking, indentation and navigation support for the Elixir. So both modes are different, emacs-elixir is a Elixir language major mode and alchemist a minor mode to help developers to work with emacs and elixir better. 

There already a lot of things moved out from the Elixir emacs-elixir mode into alchemist and already are deprecated. 

> Alchemist seems to take the menu of elixir-mode

Alchemist comes with no menu so far, so what you see might be just the elixir-mode menu with comes with emacs-elixir.

I'm not sure I answered your question right :)
