### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by seemsindie** [tonini/alchemist.el#55]
Hello,

I am a rookie when it comes to emacs and lisp, and i have trouble getting this to work.

I have added this:
(add-hook 'after-init-hook 'global-company-mode) 
(add-to-list 'auto-mode-alist '("\\.ex$" . alchemist-mode))
(add-to-list 'auto-mode-alist '("\\.exs$" . alchemist-mode))

But neither syntax highlighting or auto complete are working, any ideas or a manual for how to use this? README.md is not very clear for me...

Thanks, Ivan.

**Comment by rranelli** [comment]
Hi @seemsindie,

Syntax highlighting and basic Elixir integration is provided by [elixir-mode](http://github.com/elixir-lang/emacs-elixir)

In order to get autocomplete features you need to install and configure [company-mode](https://github.com/company-mode/company-mode)

Were you able to install the packages via Melpa? (If you're not familiar with Melpa, take a look at this [paragraph](https://github.com/milkypostman/melpa#usage))

**Comment by seemsindie** [comment]
Yes i was able to install it with melpa. I now installed elixir-mode and i have highlighting, but auto complete still don't work. For company-mode i only have:
(add-hook 'after-init-hook 'global-company-mode) 
I am not sure if i need something else...

**Comment by rranelli** [comment]
I still haven't used `company-mode`. I will switch to it and let you know what you need.

**Comment by seemsindie** [comment]
Thanks man, i appreciate it :smile:

**Comment by rranelli** [comment]
@seemsindie, I just finished adding company-mode in my Emacs setup.

First, ensure you've already installed the `company` package `(M-x package-install RET company RET)`

After installing `company`, all I had to do was add the following lines to my `init` files:

```lisp
(require 'company)
(global-company-mode)

(define-key company-active-map (kbd "C-n") 'company-select-next)
(define-key company-active-map (kbd "C-p") 'company-select-previous)
```

Seems like that's all there is to it.

**Comment by rranelli** [comment]
@seemsindie Have you figured everything out?

Can this issue be closed?

**Comment by seemsindie** [comment]
@rranelli Yes, thanks man!
