### ISSUE TITLE
 alchemist-mode-map breaks key-binding convention

### ISSUE THREAD

**Issue by andreas-roehler** [tonini/alchemist.el#59]
As some keys got broken, checking for the reasons:  alchemist-mode-map displayed a violation of 

http://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html

Don't define C-c letter as a key in Lisp programs. Sequences consisting of C-c and a letter (either upper or lower case) are reserved for users;

**Comment by jtmoulia** [comment]
Reading further:

> Sequences consisting of C-c followed by a control character or a digit are reserved for major modes. 

<kbd>C-c C-a</kbd> is undefined in vanilla Emacs...

**Comment by andreas-roehler** [comment]
At stake here are setting like that:

(define-key map (kbd "C-c a t") 'alchemist-mix-test)

i.e C-c followed by a letter.

**Comment by jtmoulia** [comment]
I'd be curious what others think, but the manual's opinion is clear:

> Please comply with it. 

But, it is rough to change keybindings. Does having a user called function which sets up the <kbd>C-c a</kbd> prefix comply with it?

**Comment by andreas-roehler** [comment]
Beside the bug, changing the bindings seems to pay WRT to efficiency.
As the bindings are mode-specific, could use for example the one below, which are in fact just two-key sequences against three keys now.

        (define-key map [(control c)(control p)] 'beginning-of-statement)
        (define-key map [(control c)(control n)] 'end-of-statement)
        (define-key map [(control c)(control u)] 'beginning-of-block)
        (define-key map [(control c)(control q)] 'end-of-block)
        (define-key map [(control meta a)] 'beginning-of-def-or-class)
        (define-key map [(control meta e)] 'end-of-def-or-class)

**Comment by rranelli** [comment]
The approach taken by [neotree](http://github.com/jaypei/emacs-neotree) is to use a custom variable for defining the desired keybinding scheme. The user has the option for using a *concise* or a *verbose* set up.

You can see how this is achieved in here:
(https://github.com/jaypei/emacs-neotree/blob/dev/neotree.el#L221)
(https://github.com/jaypei/emacs-neotree/blob/dev/neotree.el#L409)

I think this is a good approach. I personally would not use the <kbd>C-c C-*</kbd> keys myself. I really prefer the <kbd>C-c [minor mode key]</kbd> "convention".

**Comment by jtmoulia** [comment]
Thanks @rranelli -- makes sense!

Two questions:

1. Will the default change from <kbd>C-c a</kbd>, as the manual recommends?
2. Is it better to have a *concise* vs *verbose* setup, or allow the user to specify the alchemist key prefix?

That being said, it looks like there are [two bindings](https://github.com/tonini/alchemist.el/blob/master/alchemist.el#L106) which don't use the common prefix. The manual has much less to say re keybinding conventions for <kbd>M-*</kbd>.

**Comment by rranelli** [comment]
I think that `*definition-at-point` (not so sure about `*jump-back`, never used it myself in other modes) is pretty standard for all modes, so I think we should not be concerned with it.

Modes that provide language/context sensitive navigation tend to use the <kbd>M-.</kbd> key. Examples of this are `emacs-lisp-mode` with `find-function-at-point`, Robe for Ruby and Haskell mode.

**Comment by rranelli** [comment]
I think that adding a key prefix for `alchemist-mode-map` is something called for, whether or not we decide for something like a *concise* vs *verbose* option.

I don't know what to do about the first question. I have very little regard for defaults and recommendations, haha.

**Comment by jtmoulia** [comment]
awesome, sounds good to me.

I'm trying to think of not so shocking ways to change the prefix -- it'd be nice if there was a way to not change the keybindings if someone is upgrading vs installing it new.

Maybe support both prefixes for a certain number of releases, with an annoying message if the <kbd>C-c a</kbd> prefix is being used without it being explicitly set as the alchemist prefix.
