### ISSUE TITLE
disable applications startup (--no-start) when running tests

### ISSUE THREAD

**Issue by larshesel** [tonini/alchemist.el#60]
I would be fantastic if I could customize alchemist so it does not automatically start the application when running tests from the 'test-on-save' hook.

If this feature is already there, I apologize. I've been looking for a while now, but failed to find it.

**Comment by jtmoulia** [comment]
Hey @larshesel, if/when it gets merged, https://github.com/tonini/alchemist.el/issues/58 will allow you to customize the options which are passed to `mix test`:

```elisp
(set-variable 'alchemist-mix-test-default-options
      (add-to-list 'alchemist-mix-test-default-options "--no-start"))
```

A drawback is that unless you make the variable local to the buffer, the change will be global within Emacs. Would this sort of solution work for you?

**Comment by larshesel** [comment]
I think that would be pretty cool. I think for me it would be fine that it's Emacs global. Maybe it would be even better to configure this behavior in mix itself. I'd actually want mix test to, by default, run with --no-start'.

**Comment by jtmoulia** [comment]
Yup, I agree that being able to configure mix or exunit itself would be excellent -- this would be a good project level config. The [elixir-lang mailing list](https://groups.google.com/forum/#!forum/elixir-lang-talk) might be a good place to ask about that.

Another possible change: if `alchemist-mix-test` is called with a prefix arg, e.g. <kbd>C-u C-c a t</kbd>, prompt the user for the `mix test` options.

**Comment by rranelli** [comment]
The [magit](http://github.com/magit/magit) interface is *incredible* for defining command options (things like `-e` trigger the `--no-edit` option). Mimicking magit's interface would be quite nice.

**Comment by jtmoulia** [comment]
Re the magit interface -- maybe setup a context menu for [discover.el](https://github.com/mickeynp/discover.el) if it's installed. Looks pretty straightforward.

**Comment by larshesel** [comment]
I've asked about the mix configuration route over on the mailing list: https://groups.google.com/forum/#!topic/elixir-lang-talk/YCWfXQMRL1Y

**Comment by larshesel** [comment]
And José already solved the problem: https://groups.google.com/d/msg/elixir-lang-talk/YCWfXQMRL1Y/uWuu777cLO4J which is a really good solution for me (the right one IMHO) so I'll close this issue now.

Thanks a lot guys!
