### ISSUE TITLE
void alchemist-mode-map

### ISSUE THREAD

**Issue by andreas-roehler** [tonini/alchemist.el#63]
Debugger entered--Lisp error: (void-variable alchemist-mode-map)
  

IIUC the reason is defining the menu before  alchemist-mode-map is initialised.

Maybe a (defvar  alchemist-mode-map nil) before solves it.

Resp. start with the map, here an example from python.el

(defvar python-mode-map
  (let ((map (make-sparse-keymap)))
    ;; Movement
    (define-key map [remap backward-sentence] 'python-nav-backward-block)
    (define-key map [remap forward-sentence] 'python-nav-forward-block)
    (define-key map [remap backward-up-list] 'python-nav-backward-up-list)
    (define-key map "\C-c\C-j" 'imenu)
    ;; Indent specific
    (define-key map "\177" 'python-indent-dedent-line-backspace)
    (define-key map (kbd "<backtab>") 'python-indent-dedent-line)
    (define-key map "\C-c<" 'python-indent-shift-left)
    (define-key map "\C-c>" 'python-indent-shift-right)
...

**Comment by jtmoulia** [comment]
Cool -- was this fixed by #65?

**Comment by rranelli** [comment]
Yes! I could sware I added the "closes" somewhere.

This issue can be closed.
