### ISSUE TITLE
Tab completion inside IEx buffer

### ISSUE THREAD

**Issue by leohahn** [tonini/alchemist.el#72]
Is it just me or tab completion inside IEx buffer does not work? That is the only problem, right now I am using a normal terminal because of that.

If it is so, is there any work around?

**Comment by tonini** [comment]
@leohahn at the moment there is no default binding for `company-complete` (alchemist's complete mechanism works with [company](http://company-mode.github.io/))

Maybe we should start thinking about adding `TAB` as default for `company-complete` inside `*Alchemist-IEx*` buffer

**Comment by tonini** [comment]
@leohahn I'm working on an way to enable `company-complete` as default via `\t` / `TAB` https://github.com/tonini/alchemist.el/pull/73

**Comment by leohahn** [comment]
@tonini thanks for helping.
