### ISSUE TITLE
Alchemist IEx buffer: clear/0

### ISSUE THREAD

**Issue by leohahn** [tonini/alchemist.el#76]
Inside the *Alchemist-IEx* buffer:

- the command clear is accepted by the buffer, but it does not clear the screen. I am thinking that maybe it is an issue with shell or eshell? here using clear on shell or eshell does not work, but using inside term and ansi-term works fine.

EDIT

So I realize that you can use erase-buffer inside eshell. So maybe this issue is not that important anymore.

**Comment by tonini** [comment]
Thats because Alchemist use the comint library to implement a command
interpreter. We could realize a buffer clear function like @bbatsov showed
in this article http://emacsredux.com/blog/2015/01/18/clear-comint-buffers/

Leonardo Hahn <notifications@github.com> schrieb am So., 17. Mai 2015 21:34:

**Comment by bbatsov** [comment]
That very same function will be in Emacs 25.1, btw.

**Comment by tonini** [comment]
Thats great to hear, did you contribute that? :)

Bozhidar Batsov <notifications@github.com> schrieb am So., 17. Mai 2015
21:43:

**Comment by bbatsov** [comment]
Yep. :-)

On 17 May 2015 at 22:44, Samuel Tonini <notifications@github.com> wrote:

> Thats great to hear, did you contribute that? :)
>
> Bozhidar Batsov <notifications@github.com> schrieb am So., 17. Mai 2015
> 21:43:
>
> > That very same function will be in Emacs 25.1, btw.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/tonini/alchemist.el/issues/76#issuecomment-102843194
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tonini/alchemist.el/issues/76#issuecomment-102843237>.
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by tonini** [comment]
Congrats :) I'm too afraid to try contribute to emacs, I heard nightmare
stories about it :P

Bozhidar Batsov <notifications@github.com> schrieb am So., 17. Mai 2015
21:55:

> Yep. :-)
>

**Comment by leohahn** [comment]
That's nice, thanks for the tip.

**Comment by tonini** [comment]
@leohahn do you want to implement that for `alchemist-iex`? :) Would be nice, otherwise I'll do it.

**Comment by leohahn** [comment]
I you are in no hurry I can try to do that. But it would maybe take some time because I have no experience in emacs lisp. But I would be glad to help.

**Comment by tonini** [comment]
@leohahn Please go ahead :)

**Comment by leohahn** [comment]
@tonini from what I've seen, the function alchemist-iex-clear-buffer is already implemented, which is exactly the comint-clear-buffer. ^^

**Comment by tonini** [comment]
Oh! :-) maybe we should add the alchemist-mode in the iex buffdf to get all the other keybindings too

**Comment by leohahn** [comment]
Yeah, for me the mode is really nice right now with the clear-buffer command. 
Maybe it would be nice to add a default key binding, something like "C-c a c" or something like it. I didn't do it because I feel that is kind of a design decision, haha

**Comment by tonini** [comment]
I guess we should come up with kind of a minor mode for the `alchemist-iex` buffer.

**Comment by tonini** [comment]
I added a few useful keybindings to the `alchemist-iex-mode` https://github.com/tonini/alchemist.el/commit/e3d98ff34a0326149b8299bde806bb92d94404a2

/cc @pragdave maybe you find these also useful.
