### ISSUE TITLE
error when performing a definition lookup

### ISSUE THREAD

**Issue by sammyt** [tonini/alchemist.el#79]
When I run `alchemist-goto-definition-at-point` I get the following error.

```
Symbol's value as variable is void: find-tag-marker-ring
```

A bit of searching turned up [some](https://github.com/haskell/haskell-mode/issues/459) [other](https://lists.gnu.org/archive/html/bug-apl/2014-08/msg00104.html) projects seeing the same error 

I'm using GNU Emacs 24.5.1

**Comment by tonini** [comment]
Thanks for reporting :heart:
