### ISSUE TITLE
Completion throws away module name

### ISSUE THREAD

**Issue by larshesel** [tonini/alchemist.el#87]
If I enter `Keyword.fetch`and wait a bit, one suggestion is shown `Keyword.fetch!`. If I then press enter or tab `Keyword.fetch` is replaced with only `fetch!` not `Keyword.fetch!` as expected.

**Comment by tonini** [comment]
Hm, I can't reproduce it.

**Comment by larshesel** [comment]
I've seen this behaviour before - but it's not presented itself for some weeks now and suddenly showed itself again now. I actually how two emacsen open (different instances) and in one there's this behaviour and the other it's not!

**Comment by larshesel** [comment]
This might be a company-mode issue - I'll close it for now.

**Comment by tonini** [comment]
Thanks for the report!
