### ISSUE TITLE
alchemist-goto-list-symbol-definition tiny bug

### ISSUE THREAD

**Issue by whatyouhide** [tonini/alchemist.el#92]
Definitions with a `do...end` or a `do:` are handled perfectly, but bodyless clauses (used for documenting arguments and setting default argument values) cause some problems:

![screen shot 2015-06-01 at 21 48 20](https://cloud.githubusercontent.com/assets/3890250/7921797/359da5ae-08a8-11e5-82cb-c55c63437a93.png)

In the example above, `dgettext/4` is defined as:

```elixir
@spec dgettext(module, binary, binary, bindings) :: binary
def dgettext(backend, domain, msgid, bindings \\ %{})

def dgettext(backend, domain, msgid, bindings) when is_list(bindings) do
  dgettext(backend, domain, msgid, Enum.into(bindings, %{}))
end

def dgettext(backend, domain, msgid, bindings) do
   backend.lgettext(locale(), domain, msgid, bindings)
  |> handle_backend_result
end
```

`dngettext/6` is very similar.

**Comment by tonini** [comment]
Thanks for the report, I will work on that that as soon I can. :-)

**Comment by whatyouhide** [comment]
:+1: awesome, thanks :D
