### ISSUE TITLE
No font face colours or company mode help

### ISSUE THREAD

**Issue by bhrgunatha** [tonini/alchemist.el#93]
Since I updated alchemist last week there are no font face colours being applied.
I have my init.el set to auto load alchemist-mode when I open an .ex or .exs file.

The mode line shows is Elixir, alchemist **and** company, but there are no completions nor suggestions when I type and there are no font face colours. Other modes work fine, and alchemist was working correctly about 2 weeks ago.

When I click [Elixir | Text Properties | Display faces](http://i.imgur.com/INus0Dn.png) it shows lots of font faces in the colours of my colour theme (moe-dark). They all look correct, but they aren't applied as you can see in the top half..

I'm also getting no support at all with company mode.

I suspect I've configured something wrongly but can't work out what. I haven't changed anything related to alchemist in my init.el.

Any ideas 

EDIT: Sorry - I should add:
Emacs : GNU Emacs 24.5.1
Company version : 0.9.0-cvs
Elixir version: Elixir 1.0.4
aclehmist-mode : 0.16.1
elixir-mode : 1.0.0

**Comment by tonini** [comment]
Hi,

That's sounds really strange. I would like to help you, are you available on irc? Im in the #elixir-lang channel under the nickname **tonini**.

I would like to see your `init.el` file because of your custom alchemist-mode loading (actually alchemist-mode getting loaded by default with elixir-mode)

**Comment by bhrgunatha** [comment]
I can join irc yes, but for the record all I'm doing in my init.el is:

    ;; Elixir
    (add-to-list 'auto-mode-alist '("\\.ex$"       . alchemist-mode))
    (add-to-list 'auto-mode-alist '("\\.exs$"      . alchemist-mode))

**Comment by bhrgunatha** [comment]
So thanks to tonini - it seems I had an issue with company mode.

I had:
    (add-hook 'after-init-hook 'global-company-mode)

It seems the combination of company-mode, elixir-mode and alchemist-mode wasn't handled so well by package.el (which is how I installed alchemist)

Now my working solution - thanks to tonini:

I removed these 3 lines:

    (add-hook 'after-init-hook 'global-company-mode)
    (add-to-list 'auto-mode-alist '("\\.ex$"       . alchemist-mode))
    (add-to-list 'auto-mode-alist '("\\.exs$"      . alchemist-mode))

And I added these 3 lines:

    (global-company-mode)
    (require 'elixir-mode)
    (require 'alchemist)


Viola I have everything working agani.

Thanks tonini for your help - and more importantly for making alchemist-mode!

**Comment by tonini** [comment]
@bhrgunatha Great! Glad we could fix this. :) 

Have fun hacking Elixir :heart:
