### ISSUE TITLE
Automatically insert "end" when typing "do\n"

### ISSUE THREAD

**Issue by Blackrush** [tonini/alchemist.el#97]
One might use snippets instead (that's what I did back on VIM), but automatically closing `do` would apply everywhere else there aren't snippets.

What gets typed

`def start_link do\n|`

What gets inserted

```
def start_link do
  |
end
```

**Comment by tonini** [comment]
Thanks for open an issue for that.

I guess there are two good solutions to handle that with [ruby-end-mode](https://github.com/rejeep/ruby-end.el) or [smartparens](https://github.com/Fuco1/smartparens). 
https://github.com/elixir-lang/emacs-elixir#notes

**Comment by rranelli** [comment]
Please, give a go at smartparens.

It is downright amazing. I've switched from a complicated setup using paredit, wrap-region, ruby-end-mode and many more to just smartparens and never looked back since.

**Comment by tonini** [comment]
@rranelli is right, I'm getting slowly into smartparens but its really create so far.

I tried that yesterday, and so far it looks good.

### Closing pair for `do` `end` example

```lisp
(defun my-elixir-do-end-close-action (id action context)
  (when (eq action 'insert)
    (newline-and-indent)
    (previous-line)
    (indent-according-to-mode)))

(sp-with-modes '(elixir-mode)
  (sp-local-pair "do" "end"
         :when '(("SPC" "RET"))
         :post-handlers '(:add my-elixir-do-end-close-action)
         :actions '(insert)))
```

**Comment by tonini** [comment]
I close this one because I think this kind of functionality should belong to the minor modes which does this already :)

Thanks

**Comment by Blackrush** [comment]
Thanks for your help!
